PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX documentation: <http://onto.fel.cvut.cz/ontologies/documentation/>
PREFIX caa-checklist: <http://onto.fel.cvut.cz/ontologies/aviation/cz/caa/cat/audit/checklist/>

CONSTRUCT {
  ?audit_finding_type rdfs:label ?label .
  ?audit_finding_type caa-checklist:has_full_order ?order .
} WHERE {
  SERVICE <http://dev.inbas.cz/openrdf-sesame/repositories/binbas-checklist> {
    ?audit_type a documentation:checklist ;
                      	caa-checklist:has_child+ ?audit_finding_type .
                    OPTIONAL {
                      ?audit_finding_type caa-checklist:has-full-text ?label ;
                                          caa-checklist:has-full-order ?order .
                      FILTER(lang(?label)=?prefLang)
                    }
                    OPTIONAL {
                      ?audit_finding_type caa-checklist:has-full-text ?label ;
                                          caa-checklist:has-full-order ?order .
                    }
    }
} ORDER BY asc(str(?order))
VALUES (?prefLang) {("cs")}
