//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.25 at 06:09:39 PM CEST 
//


package cz.cvut.kbss.adoxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attributeprofiles",
    "models",
    "applicationmodels",
    "modelgroups"
})
@XmlRootElement(name = "ADOXML")
public class ADOXML {

    @XmlAttribute(name = "version", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String version;
    @XmlAttribute(name = "date", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String date;
    @XmlAttribute(name = "time", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String time;
    @XmlAttribute(name = "database")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String database;
    @XmlAttribute(name = "username")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String username;
    @XmlAttribute(name = "adoversion", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String adoversion;
    @XmlElement(name = "ATTRIBUTEPROFILES")
    protected ATTRIBUTEPROFILES attributeprofiles;
    @XmlElement(name = "MODELS")
    protected MODELS models;
    @XmlElement(name = "APPLICATIONMODELS")
    protected APPLICATIONMODELS applicationmodels;
    @XmlElement(name = "MODELGROUPS")
    protected MODELGROUPS modelgroups;

    /**
     * Gets the value of the version property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the date property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the time property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTime(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the database property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDatabase() {
        return database;
    }

    /**
     * Sets the value of the database property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDatabase(String value) {
        this.database = value;
    }

    /**
     * Gets the value of the username property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the adoversion property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAdoversion() {
        return adoversion;
    }

    /**
     * Sets the value of the adoversion property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAdoversion(String value) {
        this.adoversion = value;
    }

    /**
     * Gets the value of the attributeprofiles property.
     *
     * @return
     *     possible object is
     *     {@link ATTRIBUTEPROFILES }
     *
     */
    public ATTRIBUTEPROFILES getATTRIBUTEPROFILES() {
        return attributeprofiles;
    }

    /**
     * Sets the value of the attributeprofiles property.
     *
     * @param value
     *     allowed object is
     *     {@link ATTRIBUTEPROFILES }
     *
     */
    public void setATTRIBUTEPROFILES(ATTRIBUTEPROFILES value) {
        this.attributeprofiles = value;
    }

    /**
     * Gets the value of the models property.
     *
     * @return
     *     possible object is
     *     {@link MODELS }
     *
     */
    public MODELS getMODELS() {
        return models;
    }

    /**
     * Sets the value of the models property.
     *
     * @param value
     *     allowed object is
     *     {@link MODELS }
     *
     */
    public void setMODELS(MODELS value) {
        this.models = value;
    }

    /**
     * Gets the value of the applicationmodels property.
     *
     * @return
     *     possible object is
     *     {@link APPLICATIONMODELS }
     *
     */
    public APPLICATIONMODELS getAPPLICATIONMODELS() {
        return applicationmodels;
    }

    /**
     * Sets the value of the applicationmodels property.
     *
     * @param value
     *     allowed object is
     *     {@link APPLICATIONMODELS }
     *
     */
    public void setAPPLICATIONMODELS(APPLICATIONMODELS value) {
        this.applicationmodels = value;
    }

    /**
     * Gets the value of the modelgroups property.
     *
     * @return
     *     possible object is
     *     {@link MODELGROUPS }
     *
     */
    public MODELGROUPS getMODELGROUPS() {
        return modelgroups;
    }

    /**
     * Sets the value of the modelgroups property.
     *
     * @param value
     *     allowed object is
     *     {@link MODELGROUPS }
     *
     */
    public void setMODELGROUPS(MODELGROUPS value) {
        this.modelgroups = value;
    }

}
