//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.25 at 06:09:39 PM CEST 
//


package cz.cvut.kbss.adoxml;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attributeprofile",
    "attrprofdir"
})
@XmlRootElement(name = "ATTRPROFDIR")
public class ATTRPROFDIR {

    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlElement(name = "ATTRIBUTEPROFILE")
    protected List<ATTRIBUTEPROFILE> attributeprofile;
    @XmlElement(name = "ATTRPROFDIR")
    protected List<ATTRPROFDIR> attrprofdir;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the attributeprofile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeprofile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getATTRIBUTEPROFILE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ATTRIBUTEPROFILE }
     * 
     * 
     */
    public List<ATTRIBUTEPROFILE> getATTRIBUTEPROFILE() {
        if (attributeprofile == null) {
            attributeprofile = new ArrayList<ATTRIBUTEPROFILE>();
        }
        return this.attributeprofile;
    }

    /**
     * Gets the value of the attrprofdir property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attrprofdir property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getATTRPROFDIR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ATTRPROFDIR }
     * 
     * 
     */
    public List<ATTRPROFDIR> getATTRPROFDIR() {
        if (attrprofdir == null) {
            attrprofdir = new ArrayList<ATTRPROFDIR>();
        }
        return this.attrprofdir;
    }

}
