//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.25 at 06:09:39 PM CEST 
//


package cz.cvut.kbss.adoxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attrprofdirOrATTRIBUTEPROFILE"
})
@XmlRootElement(name = "ATTRIBUTEPROFILES")
public class ATTRIBUTEPROFILES {

    @XmlElements({
        @XmlElement(name = "ATTRPROFDIR", required = true, type = ATTRPROFDIR.class),
        @XmlElement(name = "ATTRIBUTEPROFILE", required = true, type = ATTRIBUTEPROFILE.class)
    })
    protected List<Object> attrprofdirOrATTRIBUTEPROFILE;

    /**
     * Gets the value of the attrprofdirOrATTRIBUTEPROFILE property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attrprofdirOrATTRIBUTEPROFILE property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getATTRPROFDIROrATTRIBUTEPROFILE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ATTRPROFDIR }
     * {@link ATTRIBUTEPROFILE }
     * 
     * 
     */
    public List<Object> getATTRPROFDIROrATTRIBUTEPROFILE() {
        if (attrprofdirOrATTRIBUTEPROFILE == null) {
            attrprofdirOrATTRIBUTEPROFILE = new ArrayList<Object>();
        }
        return this.attrprofdirOrATTRIBUTEPROFILE;
    }

}
