//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.25 at 06:09:39 PM CEST 
//


package cz.cvut.kbss.adoxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "IREF")
public class IREF {

    @XmlAttribute(name = "type", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "tmodeltype", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tmodeltype;
    @XmlAttribute(name = "tmodelname", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tmodelname;
    @XmlAttribute(name = "tmodelver", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tmodelver;
    @XmlAttribute(name = "tclassname")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tclassname;
    @XmlAttribute(name = "tobjname")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tobjname;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the tmodeltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTmodeltype() {
        return tmodeltype;
    }

    /**
     * Sets the value of the tmodeltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTmodeltype(String value) {
        this.tmodeltype = value;
    }

    /**
     * Gets the value of the tmodelname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTmodelname() {
        return tmodelname;
    }

    /**
     * Sets the value of the tmodelname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTmodelname(String value) {
        this.tmodelname = value;
    }

    /**
     * Gets the value of the tmodelver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTmodelver() {
        return tmodelver;
    }

    /**
     * Sets the value of the tmodelver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTmodelver(String value) {
        this.tmodelver = value;
    }

    /**
     * Gets the value of the tclassname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTclassname() {
        return tclassname;
    }

    /**
     * Sets the value of the tclassname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTclassname(String value) {
        this.tclassname = value;
    }

    /**
     * Gets the value of the tobjname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTobjname() {
        return tobjname;
    }

    /**
     * Sets the value of the tobjname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTobjname(String value) {
        this.tobjname = value;
    }

}
