//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.25 at 06:09:39 PM CEST 
//


package cz.cvut.kbss.adoxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attributeOrRECORD"
})
@XmlRootElement(name = "MODELATTRIBUTES")
public class MODELATTRIBUTES {

    @XmlElements({
        @XmlElement(name = "ATTRIBUTE", type = ATTRIBUTE.class),
        @XmlElement(name = "RECORD", type = RECORD.class)
    })
    protected List<Object> attributeOrRECORD;

    /**
     * Gets the value of the attributeOrRECORD property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeOrRECORD property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getATTRIBUTEOrRECORD().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ATTRIBUTE }
     * {@link RECORD }
     * 
     * 
     */
    public List<Object> getATTRIBUTEOrRECORD() {
        if (attributeOrRECORD == null) {
            attributeOrRECORD = new ArrayList<Object>();
        }
        return this.attributeOrRECORD;
    }

}
