//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.25 at 06:09:39 PM CEST 
//


package cz.cvut.kbss.adoxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modelattributes",
    "instance",
    "connector"
})
@XmlRootElement(name = "MODEL")
public class MODEL {

    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "version", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String version;
    @XmlAttribute(name = "modeltype", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String modeltype;
    @XmlAttribute(name = "libtype", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String libtype;
    @XmlAttribute(name = "applib", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String applib;
    @XmlElement(name = "MODELATTRIBUTES", required = true)
    protected MODELATTRIBUTES modelattributes;
    @XmlElement(name = "INSTANCE")
    protected List<INSTANCE> instance;
    @XmlElement(name = "CONNECTOR")
    protected List<CONNECTOR> connector;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the modeltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModeltype() {
        return modeltype;
    }

    /**
     * Sets the value of the modeltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModeltype(String value) {
        this.modeltype = value;
    }

    /**
     * Gets the value of the libtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibtype() {
        return libtype;
    }

    /**
     * Sets the value of the libtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibtype(String value) {
        this.libtype = value;
    }

    /**
     * Gets the value of the applib property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplib() {
        return applib;
    }

    /**
     * Sets the value of the applib property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplib(String value) {
        this.applib = value;
    }

    /**
     * Gets the value of the modelattributes property.
     * 
     * @return
     *     possible object is
     *     {@link MODELATTRIBUTES }
     *     
     */
    public MODELATTRIBUTES getMODELATTRIBUTES() {
        return modelattributes;
    }

    /**
     * Sets the value of the modelattributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link MODELATTRIBUTES }
     *     
     */
    public void setMODELATTRIBUTES(MODELATTRIBUTES value) {
        this.modelattributes = value;
    }

    /**
     * Gets the value of the instance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getINSTANCE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link INSTANCE }
     * 
     * 
     */
    public List<INSTANCE> getINSTANCE() {
        if (instance == null) {
            instance = new ArrayList<INSTANCE>();
        }
        return this.instance;
    }

    /**
     * Gets the value of the connector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCONNECTOR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CONNECTOR }
     * 
     * 
     */
    public List<CONNECTOR> getCONNECTOR() {
        if (connector == null) {
            connector = new ArrayList<CONNECTOR>();
        }
        return this.connector;
    }

}
