//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.25 at 06:09:39 PM CEST 
//


package cz.cvut.kbss.adoxml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.cvut.kbss.adoxml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.cvut.kbss.adoxml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MODELGROUPS }
     * 
     */
    public MODELGROUPS createMODELGROUPS() {
        return new MODELGROUPS();
    }

    /**
     * Create an instance of {@link MODELGROUP }
     * 
     */
    public MODELGROUP createMODELGROUP() {
        return new MODELGROUP();
    }

    /**
     * Create an instance of {@link ATTRIBUTE }
     * 
     */
    public ATTRIBUTE createATTRIBUTE() {
        return new ATTRIBUTE();
    }

    /**
     * Create an instance of {@link MODELREFERENCE }
     * 
     */
    public MODELREFERENCE createMODELREFERENCE() {
        return new MODELREFERENCE();
    }

    /**
     * Create an instance of {@link ADOXML }
     * 
     */
    public ADOXML createADOXML() {
        return new ADOXML();
    }

    /**
     * Create an instance of {@link ATTRIBUTEPROFILES }
     * 
     */
    public ATTRIBUTEPROFILES createATTRIBUTEPROFILES() {
        return new ATTRIBUTEPROFILES();
    }

    /**
     * Create an instance of {@link MODELS }
     * 
     */
    public MODELS createMODELS() {
        return new MODELS();
    }

    /**
     * Create an instance of {@link APPLICATIONMODELS }
     * 
     */
    public APPLICATIONMODELS createAPPLICATIONMODELS() {
        return new APPLICATIONMODELS();
    }

    /**
     * Create an instance of {@link RECORD }
     * 
     */
    public RECORD createRECORD() {
        return new RECORD();
    }

    /**
     * Create an instance of {@link ROW }
     * 
     */
    public ROW createROW() {
        return new ROW();
    }

    /**
     * Create an instance of {@link IREF }
     * 
     */
    public IREF createIREF() {
        return new IREF();
    }

    /**
     * Create an instance of {@link INSTANCE }
     * 
     */
    public INSTANCE createINSTANCE() {
        return new INSTANCE();
    }

    /**
     * Create an instance of {@link INTERREF }
     * 
     */
    public INTERREF createINTERREF() {
        return new INTERREF();
    }

    /**
     * Create an instance of {@link ATTRIBUTEPROFILE }
     * 
     */
    public ATTRIBUTEPROFILE createATTRIBUTEPROFILE() {
        return new ATTRIBUTEPROFILE();
    }

    /**
     * Create an instance of {@link MODEL }
     * 
     */
    public MODEL createMODEL() {
        return new MODEL();
    }

    /**
     * Create an instance of {@link MODELATTRIBUTES }
     * 
     */
    public MODELATTRIBUTES createMODELATTRIBUTES() {
        return new MODELATTRIBUTES();
    }

    /**
     * Create an instance of {@link CONNECTOR }
     * 
     */
    public CONNECTOR createCONNECTOR() {
        return new CONNECTOR();
    }

    /**
     * Create an instance of {@link FROM }
     * 
     */
    public FROM createFROM() {
        return new FROM();
    }

    /**
     * Create an instance of {@link APPLICATIONMODEL }
     * 
     */
    public APPLICATIONMODEL createAPPLICATIONMODEL() {
        return new APPLICATIONMODEL();
    }

    /**
     * Create an instance of {@link ATTRPROFDIR }
     * 
     */
    public ATTRPROFDIR createATTRPROFDIR() {
        return new ATTRPROFDIR();
    }

    /**
     * Create an instance of {@link TO }
     * 
     */
    public TO createTO() {
        return new TO();
    }

}
