package cz.cvut.kbss.inbas.audit.util;

/**
 * Vocabulary for the domain model.
 *
 * @author ledvima1
 */
public class Vocabulary {

    // This file is hand-written, it was not generated by OWL2Java

    public static final String CorrectiveMeasure = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#CorrectiveMeasure";
    public static final String EventReport = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#EventReport";
    public static final String EventType = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#EventType";
    public static final String EventTypeAssessment = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#EventTypeAssessment";
    public static final String Person = "http://xmlns.com/foaf/0.1/Person";
    public static final String Resource = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#Resource";
    public static final String SeverityAssessment = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#severityLevel";

    public static final String p_hasResource = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasResource";
    public static final String p_severityLevel = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#severityLevel";
    public static final String p_firstName = "http://xmlns.com/foaf/0.1/firstName";
    public static final String p_lastName = "http://xmlns.com/foaf/0.1/lastName";
    public static final String p_label = "http://www.w3.org/2000/01/rdf-schema#label";
    public static final String p_username = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#username";
    public static final String p_hasEventType = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasEventType";
    public static final String p_hasEvent = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasEvent";
    public static final String p_date = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#eventTime";
    public static final String p_dateCreated = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#dateCreated";
    public static final String p_dateLastEdited = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#dateLastEdited";
    public static final String p_description = "http://purl.org/dc/terms/description";
    public static final String p_factors = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasFactors";
    public static final String p_hasAuthor = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasAuthor";
    public static final String p_lastEditedBy = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#lastEditedBy";
    public static final String p_hasSeverityAssessment = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasSeverityAssessment";
    public static final String p_hasCorrectiveMeasure = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasCorrectiveMeasure";
    public static final String p_hasEventTypeAssessment = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasEventTypeAssessment";

    public static final String p_hasKey = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasKey";
}
