
package cz.cvut.inbas.eccairs.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ewaIWebServer", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EwaIWebServer {


    /**
     * 
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "About", action = "http://tempuri.org/ewaIWebServer/About")
    @WebResult(name = "AboutResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "About", targetNamespace = "http://tempuri.org/", className = "About")
    @ResponseWrapper(localName = "AboutResponse", targetNamespace = "http://tempuri.org/", className = "AboutResponse")
    public EwaResult about();

    /**
     * 
     * @param userToken
     * @param attachmentKey
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "AttachmentExists", action = "http://tempuri.org/ewaIWebServer/AttachmentExists")
    @WebResult(name = "AttachmentExistsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AttachmentExists", targetNamespace = "http://tempuri.org/", className = "AttachmentExists")
    @ResponseWrapper(localName = "AttachmentExistsResponse", targetNamespace = "http://tempuri.org/", className = "AttachmentExistsResponse")
    public EwaResult attachmentExists(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "attachmentKey", targetNamespace = "http://tempuri.org/")
        String attachmentKey);

    /**
     * 
     * @param libraryName
     * @param userToken
     * @param options
     * @param queryName
     * @param pageSize
     * @param batchSize
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "ExecuteQuery", action = "http://tempuri.org/ewaIWebServer/ExecuteQuery")
    @WebResult(name = "ExecuteQueryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExecuteQuery", targetNamespace = "http://tempuri.org/", className = "ExecuteQuery")
    @ResponseWrapper(localName = "ExecuteQueryResponse", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryResponse")
    public EwaResult executeQuery(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "libraryName", targetNamespace = "http://tempuri.org/")
        String libraryName,
        @WebParam(name = "queryName", targetNamespace = "http://tempuri.org/")
        String queryName,
        @WebParam(name = "options", targetNamespace = "http://tempuri.org/")
        Integer options,
        @WebParam(name = "pageSize", targetNamespace = "http://tempuri.org/")
        Integer pageSize,
        @WebParam(name = "batchSize", targetNamespace = "http://tempuri.org/")
        Integer batchSize);

    /**
     * 
     * @param libraryName
     * @param userToken
     * @param options
     * @param queryName
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "ExecuteQueryAsTable", action = "http://tempuri.org/ewaIWebServer/ExecuteQueryAsTable")
    @WebResult(name = "ExecuteQueryAsTableResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExecuteQueryAsTable", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryAsTable")
    @ResponseWrapper(localName = "ExecuteQueryAsTableResponse", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryAsTableResponse")
    public EwaResult executeQueryAsTable(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "libraryName", targetNamespace = "http://tempuri.org/")
        String libraryName,
        @WebParam(name = "queryName", targetNamespace = "http://tempuri.org/")
        String queryName,
        @WebParam(name = "options", targetNamespace = "http://tempuri.org/")
        Integer options);

    /**
     * 
     * @param libraryName
     * @param userToken
     * @param queryName
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "ExecuteQueryCount", action = "http://tempuri.org/ewaIWebServer/ExecuteQueryCount")
    @WebResult(name = "ExecuteQueryCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExecuteQueryCount", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryCount")
    @ResponseWrapper(localName = "ExecuteQueryCountResponse", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryCountResponse")
    public EwaResult executeQueryCount(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "libraryName", targetNamespace = "http://tempuri.org/")
        String libraryName,
        @WebParam(name = "queryName", targetNamespace = "http://tempuri.org/")
        String queryName);

    /**
     * 
     * @param userToken
     * @param queryObject
     * @param options
     * @param pageSize
     * @param batchSize
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "ExecuteQueryObject", action = "http://tempuri.org/ewaIWebServer/ExecuteQueryObject")
    @WebResult(name = "ExecuteQueryObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExecuteQueryObject", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryObject")
    @ResponseWrapper(localName = "ExecuteQueryObjectResponse", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryObjectResponse")
    public EwaResult executeQueryObject(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "queryObject", targetNamespace = "http://tempuri.org/")
        String queryObject,
        @WebParam(name = "options", targetNamespace = "http://tempuri.org/")
        Integer options,
        @WebParam(name = "pageSize", targetNamespace = "http://tempuri.org/")
        Integer pageSize,
        @WebParam(name = "batchSize", targetNamespace = "http://tempuri.org/")
        Integer batchSize);

    /**
     * 
     * @param body
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "ExecuteQueryObjectRaw", action = "http://tempuri.org/ewaIWebServer/ExecuteQueryObjectRaw")
    @WebResult(name = "ExecuteQueryObjectRawResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExecuteQueryObjectRaw", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryObjectRaw")
    @ResponseWrapper(localName = "ExecuteQueryObjectRawResponse", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryObjectRawResponse")
    public EwaResult executeQueryObjectRaw(
        @WebParam(name = "body", targetNamespace = "http://tempuri.org/")
        byte[] body);

    /**
     * 
     * @param userToken
     * @param queryObject
     * @param options
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "ExecuteQueryObjectAsTable", action = "http://tempuri.org/ewaIWebServer/ExecuteQueryObjectAsTable")
    @WebResult(name = "ExecuteQueryObjectAsTableResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExecuteQueryObjectAsTable", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryObjectAsTable")
    @ResponseWrapper(localName = "ExecuteQueryObjectAsTableResponse", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryObjectAsTableResponse")
    public EwaResult executeQueryObjectAsTable(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "queryObject", targetNamespace = "http://tempuri.org/")
        String queryObject,
        @WebParam(name = "options", targetNamespace = "http://tempuri.org/")
        Integer options);

    /**
     * 
     * @param body
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "ExecuteQueryObjectAsTableRaw", action = "http://tempuri.org/ewaIWebServer/ExecuteQueryObjectAsTableRaw")
    @WebResult(name = "ExecuteQueryObjectAsTableRawResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExecuteQueryObjectAsTableRaw", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryObjectAsTableRaw")
    @ResponseWrapper(localName = "ExecuteQueryObjectAsTableRawResponse", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryObjectAsTableRawResponse")
    public EwaResult executeQueryObjectAsTableRaw(
        @WebParam(name = "body", targetNamespace = "http://tempuri.org/")
        byte[] body);

    /**
     * 
     * @param userToken
     * @param queryObject
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "ExecuteQueryObjectCount", action = "http://tempuri.org/ewaIWebServer/ExecuteQueryObjectCount")
    @WebResult(name = "ExecuteQueryObjectCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExecuteQueryObjectCount", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryObjectCount")
    @ResponseWrapper(localName = "ExecuteQueryObjectCountResponse", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryObjectCountResponse")
    public EwaResult executeQueryObjectCount(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "queryObject", targetNamespace = "http://tempuri.org/")
        String queryObject);

    /**
     * 
     * @param body
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "ExecuteQueryObjectCountRaw", action = "http://tempuri.org/ewaIWebServer/ExecuteQueryObjectCountRaw")
    @WebResult(name = "ExecuteQueryObjectCountRawResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExecuteQueryObjectCountRaw", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryObjectCountRaw")
    @ResponseWrapper(localName = "ExecuteQueryObjectCountRawResponse", targetNamespace = "http://tempuri.org/", className = "ExecuteQueryObjectCountRawResponse")
    public EwaResult executeQueryObjectCountRaw(
        @WebParam(name = "body", targetNamespace = "http://tempuri.org/")
        byte[] body);

    /**
     * 
     * @param userToken
     * @param templateName
     * @param eccairsNumber
     * @param responsibleEntity
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "FormatOccurrenceWithTemplate", action = "http://tempuri.org/ewaIWebServer/FormatOccurrenceWithTemplate")
    @WebResult(name = "FormatOccurrenceWithTemplateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FormatOccurrenceWithTemplate", targetNamespace = "http://tempuri.org/", className = "FormatOccurrenceWithTemplate")
    @ResponseWrapper(localName = "FormatOccurrenceWithTemplateResponse", targetNamespace = "http://tempuri.org/", className = "FormatOccurrenceWithTemplateResponse")
    public byte[] formatOccurrenceWithTemplate(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "eccairsNumber", targetNamespace = "http://tempuri.org/")
        String eccairsNumber,
        @WebParam(name = "responsibleEntity", targetNamespace = "http://tempuri.org/")
        Integer responsibleEntity,
        @WebParam(name = "templateName", targetNamespace = "http://tempuri.org/")
        String templateName);

    /**
     * 
     * @param userToken
     * @param templateName
     * @param occurrenceKey
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "FormatOccurrenceWithTemplateByKey", action = "http://tempuri.org/ewaIWebServer/FormatOccurrenceWithTemplateByKey")
    @WebResult(name = "FormatOccurrenceWithTemplateByKeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FormatOccurrenceWithTemplateByKey", targetNamespace = "http://tempuri.org/", className = "FormatOccurrenceWithTemplateByKey")
    @ResponseWrapper(localName = "FormatOccurrenceWithTemplateByKeyResponse", targetNamespace = "http://tempuri.org/", className = "FormatOccurrenceWithTemplateByKeyResponse")
    public byte[] formatOccurrenceWithTemplateByKey(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "occurrenceKey", targetNamespace = "http://tempuri.org/")
        String occurrenceKey,
        @WebParam(name = "templateName", targetNamespace = "http://tempuri.org/")
        String templateName);

    /**
     * 
     * @param rootRepository
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetAllSubRepositories", action = "http://tempuri.org/ewaIWebServer/GetAllSubRepositories")
    @WebResult(name = "GetAllSubRepositoriesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllSubRepositories", targetNamespace = "http://tempuri.org/", className = "GetAllSubRepositories")
    @ResponseWrapper(localName = "GetAllSubRepositoriesResponse", targetNamespace = "http://tempuri.org/", className = "GetAllSubRepositoriesResponse")
    public EwaResult getAllSubRepositories(
        @WebParam(name = "rootRepository", targetNamespace = "http://tempuri.org/")
        String rootRepository);

    /**
     * 
     * @param userToken
     * @param attachmentKey
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetAttachment", action = "http://tempuri.org/ewaIWebServer/GetAttachment")
    @WebResult(name = "GetAttachmentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAttachment", targetNamespace = "http://tempuri.org/", className = "GetAttachment")
    @ResponseWrapper(localName = "GetAttachmentResponse", targetNamespace = "http://tempuri.org/", className = "GetAttachmentResponse")
    public byte[] getAttachment(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "attachmentKey", targetNamespace = "http://tempuri.org/")
        String attachmentKey);

    /**
     * 
     * @param userToken
     * @param eccairsNumber
     * @param responsibleEntity
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetAttachmentsDetails", action = "http://tempuri.org/ewaIWebServer/GetAttachmentsDetails")
    @WebResult(name = "GetAttachmentsDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAttachmentsDetails", targetNamespace = "http://tempuri.org/", className = "GetAttachmentsDetails")
    @ResponseWrapper(localName = "GetAttachmentsDetailsResponse", targetNamespace = "http://tempuri.org/", className = "GetAttachmentsDetailsResponse")
    public EwaResult getAttachmentsDetails(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "eccairsNumber", targetNamespace = "http://tempuri.org/")
        String eccairsNumber,
        @WebParam(name = "responsibleEntity", targetNamespace = "http://tempuri.org/")
        Integer responsibleEntity);

    /**
     * 
     * @param userToken
     * @param occurrenceKey
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetAttachmentsDetailsByKey", action = "http://tempuri.org/ewaIWebServer/GetAttachmentsDetailsByKey")
    @WebResult(name = "GetAttachmentsDetailsByKeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAttachmentsDetailsByKey", targetNamespace = "http://tempuri.org/", className = "GetAttachmentsDetailsByKey")
    @ResponseWrapper(localName = "GetAttachmentsDetailsByKeyResponse", targetNamespace = "http://tempuri.org/", className = "GetAttachmentsDetailsByKeyResponse")
    public EwaResult getAttachmentsDetailsByKey(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "occurrenceKey", targetNamespace = "http://tempuri.org/")
        String occurrenceKey);

    /**
     * 
     * @param userToken
     * @param operationID
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetExecutedQuery", action = "http://tempuri.org/ewaIWebServer/GetExecutedQuery")
    @WebResult(name = "GetExecutedQueryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetExecutedQuery", targetNamespace = "http://tempuri.org/", className = "GetExecutedQuery")
    @ResponseWrapper(localName = "GetExecutedQueryResponse", targetNamespace = "http://tempuri.org/", className = "GetExecutedQueryResponse")
    public EwaResult getExecutedQuery(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "operationID", targetNamespace = "http://tempuri.org/")
        String operationID);

    /**
     * 
     * @param userToken
     * @param operationID
     * @param serializationOption
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetExecutedQueryObject", action = "http://tempuri.org/ewaIWebServer/GetExecutedQueryObject")
    @WebResult(name = "GetExecutedQueryObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetExecutedQueryObject", targetNamespace = "http://tempuri.org/", className = "GetExecutedQueryObject")
    @ResponseWrapper(localName = "GetExecutedQueryObjectResponse", targetNamespace = "http://tempuri.org/", className = "GetExecutedQueryObjectResponse")
    public EwaResult getExecutedQueryObject(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "operationID", targetNamespace = "http://tempuri.org/")
        String operationID,
        @WebParam(name = "serializationOption", targetNamespace = "http://tempuri.org/")
        Integer serializationOption);

    /**
     * 
     * @param userToken
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetLibraries", action = "http://tempuri.org/ewaIWebServer/GetLibraries")
    @WebResult(name = "GetLibrariesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLibraries", targetNamespace = "http://tempuri.org/", className = "GetLibraries")
    @ResponseWrapper(localName = "GetLibrariesResponse", targetNamespace = "http://tempuri.org/", className = "GetLibrariesResponse")
    public EwaResult getLibraries(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken);

    /**
     * 
     * @param userToken
     * @param eccairsNumber
     * @param responsibleEntity
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetOccurrence", action = "http://tempuri.org/ewaIWebServer/GetOccurrence")
    @WebResult(name = "GetOccurrenceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOccurrence", targetNamespace = "http://tempuri.org/", className = "GetOccurrence")
    @ResponseWrapper(localName = "GetOccurrenceResponse", targetNamespace = "http://tempuri.org/", className = "GetOccurrenceResponse")
    public EwaResult getOccurrence(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "eccairsNumber", targetNamespace = "http://tempuri.org/")
        String eccairsNumber,
        @WebParam(name = "responsibleEntity", targetNamespace = "http://tempuri.org/")
        Integer responsibleEntity);

    /**
     * 
     * @param userToken
     * @param occurrenceKey
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetOccurrenceByKey", action = "http://tempuri.org/ewaIWebServer/GetOccurrenceByKey")
    @WebResult(name = "GetOccurrenceByKeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOccurrenceByKey", targetNamespace = "http://tempuri.org/", className = "GetOccurrenceByKey")
    @ResponseWrapper(localName = "GetOccurrenceByKeyResponse", targetNamespace = "http://tempuri.org/", className = "GetOccurrenceByKeyResponse")
    public EwaResult getOccurrenceByKey(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "occurrenceKey", targetNamespace = "http://tempuri.org/")
        String occurrenceKey);

    /**
     * 
     * @param userToken
     * @param viewName
     * @param eccairsNumber
     * @param responsibleEntity
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetOccurrenceAsPDF", action = "http://tempuri.org/ewaIWebServer/GetOccurrenceAsPDF")
    @WebResult(name = "GetOccurrenceAsPDFResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOccurrenceAsPDF", targetNamespace = "http://tempuri.org/", className = "GetOccurrenceAsPDF")
    @ResponseWrapper(localName = "GetOccurrenceAsPDFResponse", targetNamespace = "http://tempuri.org/", className = "GetOccurrenceAsPDFResponse")
    public byte[] getOccurrenceAsPDF(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "eccairsNumber", targetNamespace = "http://tempuri.org/")
        String eccairsNumber,
        @WebParam(name = "responsibleEntity", targetNamespace = "http://tempuri.org/")
        Integer responsibleEntity,
        @WebParam(name = "viewName", targetNamespace = "http://tempuri.org/")
        String viewName);

    /**
     * 
     * @param userToken
     * @param viewName
     * @param occurrenceKey
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetOccurrenceAsPDFByKey", action = "http://tempuri.org/ewaIWebServer/GetOccurrenceAsPDFByKey")
    @WebResult(name = "GetOccurrenceAsPDFByKeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOccurrenceAsPDFByKey", targetNamespace = "http://tempuri.org/", className = "GetOccurrenceAsPDFByKey")
    @ResponseWrapper(localName = "GetOccurrenceAsPDFByKeyResponse", targetNamespace = "http://tempuri.org/", className = "GetOccurrenceAsPDFByKeyResponse")
    public byte[] getOccurrenceAsPDFByKey(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "occurrenceKey", targetNamespace = "http://tempuri.org/")
        String occurrenceKey,
        @WebParam(name = "viewName", targetNamespace = "http://tempuri.org/")
        String viewName);

    /**
     * 
     * @param userToken
     * @param eccairsNumber
     * @param responsibleEntity
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetOccurrenceData", action = "http://tempuri.org/ewaIWebServer/GetOccurrenceData")
    @WebResult(name = "GetOccurrenceDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOccurrenceData", targetNamespace = "http://tempuri.org/", className = "GetOccurrenceData")
    @ResponseWrapper(localName = "GetOccurrenceDataResponse", targetNamespace = "http://tempuri.org/", className = "GetOccurrenceDataResponse")
    public EwaResult getOccurrenceData(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "eccairsNumber", targetNamespace = "http://tempuri.org/")
        String eccairsNumber,
        @WebParam(name = "responsibleEntity", targetNamespace = "http://tempuri.org/")
        Integer responsibleEntity);

    /**
     * 
     * @param userToken
     * @param occurrenceKey
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetOccurrenceDataByKey", action = "http://tempuri.org/ewaIWebServer/GetOccurrenceDataByKey")
    @WebResult(name = "GetOccurrenceDataByKeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOccurrenceDataByKey", targetNamespace = "http://tempuri.org/", className = "GetOccurrenceDataByKey")
    @ResponseWrapper(localName = "GetOccurrenceDataByKeyResponse", targetNamespace = "http://tempuri.org/", className = "GetOccurrenceDataByKeyResponse")
    public EwaResult getOccurrenceDataByKey(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "occurrenceKey", targetNamespace = "http://tempuri.org/")
        String occurrenceKey);

    /**
     * 
     * @param userToken
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetOccurrencePrintingTemplates", action = "http://tempuri.org/ewaIWebServer/GetOccurrencePrintingTemplates")
    @WebResult(name = "GetOccurrencePrintingTemplatesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOccurrencePrintingTemplates", targetNamespace = "http://tempuri.org/", className = "GetOccurrencePrintingTemplates")
    @ResponseWrapper(localName = "GetOccurrencePrintingTemplatesResponse", targetNamespace = "http://tempuri.org/", className = "GetOccurrencePrintingTemplatesResponse")
    public EwaResult getOccurrencePrintingTemplates(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken);

    /**
     * 
     * @param libraryName
     * @param userToken
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetQueries", action = "http://tempuri.org/ewaIWebServer/GetQueries")
    @WebResult(name = "GetQueriesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetQueries", targetNamespace = "http://tempuri.org/", className = "GetQueries")
    @ResponseWrapper(localName = "GetQueriesResponse", targetNamespace = "http://tempuri.org/", className = "GetQueriesResponse")
    public EwaResult getQueries(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "libraryName", targetNamespace = "http://tempuri.org/")
        String libraryName);

    /**
     * 
     * @param userToken
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetQueriesByExample", action = "http://tempuri.org/ewaIWebServer/GetQueriesByExample")
    @WebResult(name = "GetQueriesByExampleResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetQueriesByExample", targetNamespace = "http://tempuri.org/", className = "GetQueriesByExample")
    @ResponseWrapper(localName = "GetQueriesByExampleResponse", targetNamespace = "http://tempuri.org/", className = "GetQueriesByExampleResponse")
    public EwaResult getQueriesByExample(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken);

    /**
     * 
     * @param userToken
     * @param operationID
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetQuery", action = "http://tempuri.org/ewaIWebServer/GetQuery")
    @WebResult(name = "GetQueryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetQuery", targetNamespace = "http://tempuri.org/", className = "GetQuery")
    @ResponseWrapper(localName = "GetQueryResponse", targetNamespace = "http://tempuri.org/", className = "GetQueryResponse")
    public EwaResult getQuery(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "operationID", targetNamespace = "http://tempuri.org/")
        String operationID);

    /**
     * 
     * @param userToken
     * @param queryName
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetQueryByExampleData", action = "http://tempuri.org/ewaIWebServer/GetQueryByExampleData")
    @WebResult(name = "GetQueryByExampleDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetQueryByExampleData", targetNamespace = "http://tempuri.org/", className = "GetQueryByExampleData")
    @ResponseWrapper(localName = "GetQueryByExampleDataResponse", targetNamespace = "http://tempuri.org/", className = "GetQueryByExampleDataResponse")
    public EwaResult getQueryByExampleData(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "queryName", targetNamespace = "http://tempuri.org/")
        String queryName);

    /**
     * 
     * @param userToken
     * @param queryName
     * @param serializationOption
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetQueryByExampleObject", action = "http://tempuri.org/ewaIWebServer/GetQueryByExampleObject")
    @WebResult(name = "GetQueryByExampleObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetQueryByExampleObject", targetNamespace = "http://tempuri.org/", className = "GetQueryByExampleObject")
    @ResponseWrapper(localName = "GetQueryByExampleObjectResponse", targetNamespace = "http://tempuri.org/", className = "GetQueryByExampleObjectResponse")
    public EwaResult getQueryByExampleObject(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "queryName", targetNamespace = "http://tempuri.org/")
        String queryName,
        @WebParam(name = "serializationOption", targetNamespace = "http://tempuri.org/")
        Integer serializationOption);

    /**
     * 
     * @param libraryName
     * @param userToken
     * @param queryName
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetQueryData", action = "http://tempuri.org/ewaIWebServer/GetQueryData")
    @WebResult(name = "GetQueryDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetQueryData", targetNamespace = "http://tempuri.org/", className = "GetQueryData")
    @ResponseWrapper(localName = "GetQueryDataResponse", targetNamespace = "http://tempuri.org/", className = "GetQueryDataResponse")
    public EwaResult getQueryData(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "libraryName", targetNamespace = "http://tempuri.org/")
        String libraryName,
        @WebParam(name = "queryName", targetNamespace = "http://tempuri.org/")
        String queryName);

    /**
     * 
     * @param libraryName
     * @param userToken
     * @param queryName
     * @param serializationOption
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetQueryObject", action = "http://tempuri.org/ewaIWebServer/GetQueryObject")
    @WebResult(name = "GetQueryObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetQueryObject", targetNamespace = "http://tempuri.org/", className = "GetQueryObject")
    @ResponseWrapper(localName = "GetQueryObjectResponse", targetNamespace = "http://tempuri.org/", className = "GetQueryObjectResponse")
    public EwaResult getQueryObject(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "libraryName", targetNamespace = "http://tempuri.org/")
        String libraryName,
        @WebParam(name = "queryName", targetNamespace = "http://tempuri.org/")
        String queryName,
        @WebParam(name = "serializationOption", targetNamespace = "http://tempuri.org/")
        Integer serializationOption);

    /**
     * 
     * @param userToken
     * @param operationID
     * @param page
     * @param order
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetQueryResult", action = "http://tempuri.org/ewaIWebServer/GetQueryResult")
    @WebResult(name = "GetQueryResultResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetQueryResult", targetNamespace = "http://tempuri.org/", className = "GetQueryResult")
    @ResponseWrapper(localName = "GetQueryResultResponse", targetNamespace = "http://tempuri.org/", className = "GetQueryResultResponse")
    public EwaResult getQueryResult(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "operationID", targetNamespace = "http://tempuri.org/")
        String operationID,
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        Integer page,
        @WebParam(name = "order", targetNamespace = "http://tempuri.org/")
        String order);

    /**
     * 
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetRepositories", action = "http://tempuri.org/ewaIWebServer/GetRepositories")
    @WebResult(name = "GetRepositoriesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRepositories", targetNamespace = "http://tempuri.org/", className = "GetRepositories")
    @ResponseWrapper(localName = "GetRepositoriesResponse", targetNamespace = "http://tempuri.org/", className = "GetRepositoriesResponse")
    public EwaResult getRepositories();

    /**
     * 
     * @param userToken
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetUserInfo", action = "http://tempuri.org/ewaIWebServer/GetUserInfo")
    @WebResult(name = "GetUserInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUserInfo", targetNamespace = "http://tempuri.org/", className = "GetUserInfo")
    @ResponseWrapper(localName = "GetUserInfoResponse", targetNamespace = "http://tempuri.org/", className = "GetUserInfoResponse")
    public EwaResult getUserInfo(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken);

    /**
     * 
     * @param userToken
     * @param viewName
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetViewImage", action = "http://tempuri.org/ewaIWebServer/GetViewImage")
    @WebResult(name = "GetViewImageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetViewImage", targetNamespace = "http://tempuri.org/", className = "GetViewImage")
    @ResponseWrapper(localName = "GetViewImageResponse", targetNamespace = "http://tempuri.org/", className = "GetViewImageResponse")
    public byte[] getViewImage(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "viewName", targetNamespace = "http://tempuri.org/")
        String viewName);

    /**
     * 
     * @param userToken
     * @param actionType
     * @param eccairsNumber
     * @param responsibleEntity
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetViews", action = "http://tempuri.org/ewaIWebServer/GetViews")
    @WebResult(name = "GetViewsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetViews", targetNamespace = "http://tempuri.org/", className = "GetViews")
    @ResponseWrapper(localName = "GetViewsResponse", targetNamespace = "http://tempuri.org/", className = "GetViewsResponse")
    public EwaResult getViews(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "eccairsNumber", targetNamespace = "http://tempuri.org/")
        String eccairsNumber,
        @WebParam(name = "responsibleEntity", targetNamespace = "http://tempuri.org/")
        Integer responsibleEntity,
        @WebParam(name = "actionType", targetNamespace = "http://tempuri.org/")
        Integer actionType);

    /**
     * 
     * @param userToken
     * @param actionType
     * @param occurrenceKey
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetViewsByKey", action = "http://tempuri.org/ewaIWebServer/GetViewsByKey")
    @WebResult(name = "GetViewsByKeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetViewsByKey", targetNamespace = "http://tempuri.org/", className = "GetViewsByKey")
    @ResponseWrapper(localName = "GetViewsByKeyResponse", targetNamespace = "http://tempuri.org/", className = "GetViewsByKeyResponse")
    public EwaResult getViewsByKey(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "occurrenceKey", targetNamespace = "http://tempuri.org/")
        String occurrenceKey,
        @WebParam(name = "actionType", targetNamespace = "http://tempuri.org/")
        Integer actionType);

    /**
     * 
     * @param userToken
     * @param operationID
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "IsValidQueryResult", action = "http://tempuri.org/ewaIWebServer/IsValidQueryResult")
    @WebResult(name = "IsValidQueryResultResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsValidQueryResult", targetNamespace = "http://tempuri.org/", className = "IsValidQueryResult")
    @ResponseWrapper(localName = "IsValidQueryResultResponse", targetNamespace = "http://tempuri.org/", className = "IsValidQueryResultResponse")
    public EwaResult isValidQueryResult(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "operationID", targetNamespace = "http://tempuri.org/")
        String operationID);

    /**
     * 
     * @param userToken
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "IsValidToken", action = "http://tempuri.org/ewaIWebServer/IsValidToken")
    @WebResult(name = "IsValidTokenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsValidToken", targetNamespace = "http://tempuri.org/", className = "IsValidToken")
    @ResponseWrapper(localName = "IsValidTokenResponse", targetNamespace = "http://tempuri.org/", className = "IsValidTokenResponse")
    public EwaResult isValidToken(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken);

    /**
     * 
     * @param password
     * @param language
     * @param repository
     * @param username
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "Login", action = "http://tempuri.org/ewaIWebServer/Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "LoginResponse")
    public EwaResult login(
        @WebParam(name = "repository", targetNamespace = "http://tempuri.org/")
        String repository,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "language", targetNamespace = "http://tempuri.org/")
        String language);

    /**
     * 
     * @param loginInfo
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "LoginByInfo", action = "http://tempuri.org/ewaIWebServer/LoginByInfo")
    @WebResult(name = "LoginByInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LoginByInfo", targetNamespace = "http://tempuri.org/", className = "LoginByInfo")
    @ResponseWrapper(localName = "LoginByInfoResponse", targetNamespace = "http://tempuri.org/", className = "LoginByInfoResponse")
    public EwaResult loginByInfo(
        @WebParam(name = "loginInfo", targetNamespace = "http://tempuri.org/")
        String loginInfo);

    /**
     * 
     * @param userToken
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "Logout", action = "http://tempuri.org/ewaIWebServer/Logout")
    @WebResult(name = "LogoutResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Logout", targetNamespace = "http://tempuri.org/", className = "Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://tempuri.org/", className = "LogoutResponse")
    public EwaResult logout(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken);

    /**
     * 
     * @param userToken
     * @param eccairsNumber
     * @param responsibleEntity
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "RefreshOccurrence", action = "http://tempuri.org/ewaIWebServer/RefreshOccurrence")
    @WebResult(name = "RefreshOccurrenceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RefreshOccurrence", targetNamespace = "http://tempuri.org/", className = "RefreshOccurrence")
    @ResponseWrapper(localName = "RefreshOccurrenceResponse", targetNamespace = "http://tempuri.org/", className = "RefreshOccurrenceResponse")
    public EwaResult refreshOccurrence(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "eccairsNumber", targetNamespace = "http://tempuri.org/")
        String eccairsNumber,
        @WebParam(name = "responsibleEntity", targetNamespace = "http://tempuri.org/")
        Integer responsibleEntity);

    /**
     * 
     * @param userToken
     * @param occurrenceKey
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "RefreshOccurrenceDataByKey", action = "http://tempuri.org/ewaIWebServer/RefreshOccurrenceDataByKey")
    @WebResult(name = "RefreshOccurrenceDataByKeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RefreshOccurrenceDataByKey", targetNamespace = "http://tempuri.org/", className = "RefreshOccurrenceDataByKey")
    @ResponseWrapper(localName = "RefreshOccurrenceDataByKeyResponse", targetNamespace = "http://tempuri.org/", className = "RefreshOccurrenceDataByKeyResponse")
    public EwaResult refreshOccurrenceDataByKey(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "occurrenceKey", targetNamespace = "http://tempuri.org/")
        String occurrenceKey);

    /**
     * 
     * @param userToken
     * @param operationID
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "ReleaseQueryResult", action = "http://tempuri.org/ewaIWebServer/ReleaseQueryResult")
    @WebResult(name = "ReleaseQueryResultResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReleaseQueryResult", targetNamespace = "http://tempuri.org/", className = "ReleaseQueryResult")
    @ResponseWrapper(localName = "ReleaseQueryResultResponse", targetNamespace = "http://tempuri.org/", className = "ReleaseQueryResultResponse")
    public EwaResult releaseQueryResult(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "operationID", targetNamespace = "http://tempuri.org/")
        String operationID);

    /**
     * 
     * @param body
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "SaveUserInfoRaw", action = "http://tempuri.org/ewaIWebServer/SaveUserInfoRaw")
    @WebResult(name = "SaveUserInfoRawResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SaveUserInfoRaw", targetNamespace = "http://tempuri.org/", className = "SaveUserInfoRaw")
    @ResponseWrapper(localName = "SaveUserInfoRawResponse", targetNamespace = "http://tempuri.org/", className = "SaveUserInfoRawResponse")
    public EwaResult saveUserInfoRaw(
        @WebParam(name = "body", targetNamespace = "http://tempuri.org/")
        byte[] body);

    /**
     * 
     * @param userToken
     * @param userInfo
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "SaveUserInfo", action = "http://tempuri.org/ewaIWebServer/SaveUserInfo")
    @WebResult(name = "SaveUserInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SaveUserInfo", targetNamespace = "http://tempuri.org/", className = "SaveUserInfo")
    @ResponseWrapper(localName = "SaveUserInfoResponse", targetNamespace = "http://tempuri.org/", className = "SaveUserInfoResponse")
    public EwaResult saveUserInfo(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "userInfo", targetNamespace = "http://tempuri.org/")
        String userInfo);

    /**
     * 
     * @param attributeID
     * @param userToken
     * @param serializationOptions
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetAttribute", action = "http://tempuri.org/ewaIWebServer/GetAttribute")
    @WebResult(name = "GetAttributeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAttribute", targetNamespace = "http://tempuri.org/", className = "GetAttribute")
    @ResponseWrapper(localName = "GetAttributeResponse", targetNamespace = "http://tempuri.org/", className = "GetAttributeResponse")
    public EwaResult getAttribute(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "attributeID", targetNamespace = "http://tempuri.org/")
        Integer attributeID,
        @WebParam(name = "serializationOptions", targetNamespace = "http://tempuri.org/")
        Integer serializationOptions);

    /**
     * 
     * @param userToken
     * @param serializationOptions
     * @param parentEntityID
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetAttributes", action = "http://tempuri.org/ewaIWebServer/GetAttributes")
    @WebResult(name = "GetAttributesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAttributes", targetNamespace = "http://tempuri.org/", className = "GetAttributes")
    @ResponseWrapper(localName = "GetAttributesResponse", targetNamespace = "http://tempuri.org/", className = "GetAttributesResponse")
    public EwaResult getAttributes(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "parentEntityID", targetNamespace = "http://tempuri.org/")
        Integer parentEntityID,
        @WebParam(name = "serializationOptions", targetNamespace = "http://tempuri.org/")
        Integer serializationOptions);

    /**
     * 
     * @param userToken
     * @param serializationOptions
     * @param entityID
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetEntity", action = "http://tempuri.org/ewaIWebServer/GetEntity")
    @WebResult(name = "GetEntityResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEntity", targetNamespace = "http://tempuri.org/", className = "GetEntity")
    @ResponseWrapper(localName = "GetEntityResponse", targetNamespace = "http://tempuri.org/", className = "GetEntityResponse")
    public EwaResult getEntity(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "entityID", targetNamespace = "http://tempuri.org/")
        Integer entityID,
        @WebParam(name = "serializationOptions", targetNamespace = "http://tempuri.org/")
        Integer serializationOptions);

    /**
     * 
     * @param userToken
     * @param serializationOptions
     * @param parentEntityID
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetEntities", action = "http://tempuri.org/ewaIWebServer/GetEntities")
    @WebResult(name = "GetEntitiesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEntities", targetNamespace = "http://tempuri.org/", className = "GetEntities")
    @ResponseWrapper(localName = "GetEntitiesResponse", targetNamespace = "http://tempuri.org/", className = "GetEntitiesResponse")
    public EwaResult getEntities(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "parentEntityID", targetNamespace = "http://tempuri.org/")
        Integer parentEntityID,
        @WebParam(name = "serializationOptions", targetNamespace = "http://tempuri.org/")
        Integer serializationOptions);

    /**
     * 
     * @param attributeID
     * @param userToken
     * @param serializationOptions
     * @param valueData
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetAttributeValue", action = "http://tempuri.org/ewaIWebServer/GetAttributeValue")
    @WebResult(name = "GetAttributeValueResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAttributeValue", targetNamespace = "http://tempuri.org/", className = "GetAttributeValue")
    @ResponseWrapper(localName = "GetAttributeValueResponse", targetNamespace = "http://tempuri.org/", className = "GetAttributeValueResponse")
    public EwaResult getAttributeValue(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "attributeID", targetNamespace = "http://tempuri.org/")
        Integer attributeID,
        @WebParam(name = "valueData", targetNamespace = "http://tempuri.org/")
        String valueData,
        @WebParam(name = "serializationOptions", targetNamespace = "http://tempuri.org/")
        Integer serializationOptions);

    /**
     * 
     * @param userToken
     * @param textID
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetLexiconText", action = "http://tempuri.org/ewaIWebServer/GetLexiconText")
    @WebResult(name = "GetLexiconTextResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLexiconText", targetNamespace = "http://tempuri.org/", className = "GetLexiconText")
    @ResponseWrapper(localName = "GetLexiconTextResponse", targetNamespace = "http://tempuri.org/", className = "GetLexiconTextResponse")
    public EwaResult getLexiconText(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "textID", targetNamespace = "http://tempuri.org/")
        Integer textID);

    /**
     * 
     * @param attributeID
     * @param userToken
     * @param serializationOptions
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetUnits", action = "http://tempuri.org/ewaIWebServer/GetUnits")
    @WebResult(name = "GetUnitsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUnits", targetNamespace = "http://tempuri.org/", className = "GetUnits")
    @ResponseWrapper(localName = "GetUnitsResponse", targetNamespace = "http://tempuri.org/", className = "GetUnitsResponse")
    public EwaResult getUnits(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "attributeID", targetNamespace = "http://tempuri.org/")
        Integer attributeID,
        @WebParam(name = "serializationOptions", targetNamespace = "http://tempuri.org/")
        Integer serializationOptions);

    /**
     * 
     * @param attributeID
     * @param userToken
     * @param serializationOptions
     * @param value
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetValuePath", action = "http://tempuri.org/ewaIWebServer/GetValuePath")
    @WebResult(name = "GetValuePathResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetValuePath", targetNamespace = "http://tempuri.org/", className = "GetValuePath")
    @ResponseWrapper(localName = "GetValuePathResponse", targetNamespace = "http://tempuri.org/", className = "GetValuePathResponse")
    public EwaResult getValuePath(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "attributeID", targetNamespace = "http://tempuri.org/")
        Integer attributeID,
        @WebParam(name = "value", targetNamespace = "http://tempuri.org/")
        Integer value,
        @WebParam(name = "serializationOptions", targetNamespace = "http://tempuri.org/")
        Integer serializationOptions);

    /**
     * 
     * @param attributeID
     * @param filter
     * @param lastLevel
     * @param userToken
     * @param extendedFilter
     * @param showDeletedValues
     * @param serializationOptions
     * @param parentValue
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetValues", action = "http://tempuri.org/ewaIWebServer/GetValues")
    @WebResult(name = "GetValuesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetValues", targetNamespace = "http://tempuri.org/", className = "GetValues")
    @ResponseWrapper(localName = "GetValuesResponse", targetNamespace = "http://tempuri.org/", className = "GetValuesResponse")
    public EwaResult getValues(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "attributeID", targetNamespace = "http://tempuri.org/")
        Integer attributeID,
        @WebParam(name = "parentValue", targetNamespace = "http://tempuri.org/")
        Integer parentValue,
        @WebParam(name = "filter", targetNamespace = "http://tempuri.org/")
        String filter,
        @WebParam(name = "extendedFilter", targetNamespace = "http://tempuri.org/")
        Boolean extendedFilter,
        @WebParam(name = "lastLevel", targetNamespace = "http://tempuri.org/")
        Integer lastLevel,
        @WebParam(name = "showDeletedValues", targetNamespace = "http://tempuri.org/")
        Boolean showDeletedValues,
        @WebParam(name = "serializationOptions", targetNamespace = "http://tempuri.org/")
        Integer serializationOptions);

    /**
     * 
     * @param attributeID
     * @param userToken
     * @param unitID
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "SetAttributeUnitID", action = "http://tempuri.org/ewaIWebServer/SetAttributeUnitID")
    @WebResult(name = "SetAttributeUnitIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetAttributeUnitID", targetNamespace = "http://tempuri.org/", className = "SetAttributeUnitID")
    @ResponseWrapper(localName = "SetAttributeUnitIDResponse", targetNamespace = "http://tempuri.org/", className = "SetAttributeUnitIDResponse")
    public EwaResult setAttributeUnitID(
        @WebParam(name = "userToken", targetNamespace = "http://tempuri.org/")
        String userToken,
        @WebParam(name = "attributeID", targetNamespace = "http://tempuri.org/")
        Integer attributeID,
        @WebParam(name = "unitID", targetNamespace = "http://tempuri.org/")
        Integer unitID);

    /**
     * 
     * @param userManagerToken
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "CreateUser", action = "http://tempuri.org/ewaIWebServer/CreateUser")
    @WebResult(name = "CreateUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateUser", targetNamespace = "http://tempuri.org/", className = "CreateUser")
    @ResponseWrapper(localName = "CreateUserResponse", targetNamespace = "http://tempuri.org/", className = "CreateUserResponse")
    public EwaResult createUser(
        @WebParam(name = "userManagerToken", targetNamespace = "http://tempuri.org/")
        String userManagerToken);

    /**
     * 
     * @param userManagerToken
     * @param username
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "DeleteUser", action = "http://tempuri.org/ewaIWebServer/DeleteUser")
    @WebResult(name = "DeleteUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteUser", targetNamespace = "http://tempuri.org/", className = "DeleteUser")
    @ResponseWrapper(localName = "DeleteUserResponse", targetNamespace = "http://tempuri.org/", className = "DeleteUserResponse")
    public EwaResult deleteUser(
        @WebParam(name = "userManagerToken", targetNamespace = "http://tempuri.org/")
        String userManagerToken,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username);

    /**
     * 
     * @param userManagerToken
     * @param username
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetUser", action = "http://tempuri.org/ewaIWebServer/GetUser")
    @WebResult(name = "GetUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUser", targetNamespace = "http://tempuri.org/", className = "GetUser")
    @ResponseWrapper(localName = "GetUserResponse", targetNamespace = "http://tempuri.org/", className = "GetUserResponse")
    public EwaResult getUser(
        @WebParam(name = "userManagerToken", targetNamespace = "http://tempuri.org/")
        String userManagerToken,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username);

    /**
     * 
     * @param userManagerToken
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetUsers", action = "http://tempuri.org/ewaIWebServer/GetUsers")
    @WebResult(name = "GetUsersResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUsers", targetNamespace = "http://tempuri.org/", className = "GetUsers")
    @ResponseWrapper(localName = "GetUsersResponse", targetNamespace = "http://tempuri.org/", className = "GetUsersResponse")
    public EwaResult getUsers(
        @WebParam(name = "userManagerToken", targetNamespace = "http://tempuri.org/")
        String userManagerToken);

    /**
     * 
     * @param body
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "SaveUserRaw", action = "http://tempuri.org/ewaIWebServer/SaveUserRaw")
    @WebResult(name = "SaveUserRawResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SaveUserRaw", targetNamespace = "http://tempuri.org/", className = "SaveUserRaw")
    @ResponseWrapper(localName = "SaveUserRawResponse", targetNamespace = "http://tempuri.org/", className = "SaveUserRawResponse")
    public EwaResult saveUserRaw(
        @WebParam(name = "body", targetNamespace = "http://tempuri.org/")
        byte[] body);

    /**
     * 
     * @param userManagerToken
     * @param user
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "SaveUser", action = "http://tempuri.org/ewaIWebServer/SaveUser")
    @WebResult(name = "SaveUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SaveUser", targetNamespace = "http://tempuri.org/", className = "SaveUser")
    @ResponseWrapper(localName = "SaveUserResponse", targetNamespace = "http://tempuri.org/", className = "SaveUserResponse")
    public EwaResult saveUser(
        @WebParam(name = "userManagerToken", targetNamespace = "http://tempuri.org/")
        String userManagerToken,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user);

    /**
     * 
     * @param password
     * @param repository
     * @param username
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "UserManagerLogin", action = "http://tempuri.org/ewaIWebServer/UserManagerLogin")
    @WebResult(name = "UserManagerLoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UserManagerLogin", targetNamespace = "http://tempuri.org/", className = "UserManagerLogin")
    @ResponseWrapper(localName = "UserManagerLoginResponse", targetNamespace = "http://tempuri.org/", className = "UserManagerLoginResponse")
    public EwaResult userManagerLogin(
        @WebParam(name = "repository", targetNamespace = "http://tempuri.org/")
        String repository,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param loginInfo
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "UserManagerLoginByInfo", action = "http://tempuri.org/ewaIWebServer/UserManagerLoginByInfo")
    @WebResult(name = "UserManagerLoginByInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UserManagerLoginByInfo", targetNamespace = "http://tempuri.org/", className = "UserManagerLoginByInfo")
    @ResponseWrapper(localName = "UserManagerLoginByInfoResponse", targetNamespace = "http://tempuri.org/", className = "UserManagerLoginByInfoResponse")
    public EwaResult userManagerLoginByInfo(
        @WebParam(name = "loginInfo", targetNamespace = "http://tempuri.org/")
        String loginInfo);

    /**
     * 
     * @param validityMilliseconds
     * @param userManagerToken
     * @param language
     * @param repository
     * @param username
     * @return
     *     returns EwaResult
     */
    @WebMethod(operationName = "GetImpersonatedUserCredentials", action = "http://tempuri.org/ewaIWebServer/GetImpersonatedUserCredentials")
    @WebResult(name = "GetImpersonatedUserCredentialsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetImpersonatedUserCredentials", targetNamespace = "http://tempuri.org/", className = "GetImpersonatedUserCredentials")
    @ResponseWrapper(localName = "GetImpersonatedUserCredentialsResponse", targetNamespace = "http://tempuri.org/", className = "GetImpersonatedUserCredentialsResponse")
    public EwaResult getImpersonatedUserCredentials(
        @WebParam(name = "userManagerToken", targetNamespace = "http://tempuri.org/")
        String userManagerToken,
        @WebParam(name = "repository", targetNamespace = "http://tempuri.org/")
        String repository,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "language", targetNamespace = "http://tempuri.org/")
        String language,
        @WebParam(name = "validityMilliseconds", targetNamespace = "http://tempuri.org/")
        Integer validityMilliseconds);

}
