package cz.cvut.kbss.inbas.reporting.util;

/**
 * Vocabulary for the domain model.
 */
// Model Redesing (MR)
// class DocumentedEntity - everithing should "extend" this category
//		- author
//		- date created

// class Perdurant extends Entity
// 	- time description
//	- location
// 	- 
public class Vocabulary_new {

    // This file is hand-written, it was not generated by OWL2Java

    // Report is a common superclass for all kinds of reports - initial, preliminary and investigation
    public static final String Report = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#Report"; //"http://onto.fel.cvut.cz/ontologies/documentation/report"
//    public static final String Aircraft = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#Aircraft";
    public static final String CorrectiveMeasure = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#CorrectiveMeasure"; //"http://onto.fel.cvut.cz/ontologies/aviation/documentation#corrective-measure"
	// MR- EventType and EventTypeAssessment are qustions about the Event. 
	//	- EventType asks about the category of the eveny
	// 	- EventTypeAssessment asks about a narative description and questions about the RunwayIncursion EventType
	// 		- see entity object
	// note: if 'e' is an Event, the answer 'a' (where "'a' rdfs:subclassOf ufo:Event") to the question "what is the EventType of 'e'" should be mapped to the triple "'e' rdf:type 'a'".   
    public static final String EventType = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#EventType";//"sub class of ufo:Event"
	// This should be generalized as a generic question about the event of a certain type. This class has two important 
    public static final String EventTypeAssessment = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#EventTypeAssessment";
	
    public static final String Factor = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#Factor";// TODO - not found in Aviation safety. Factor is the role played by a Situation or Event within a cause contributes/mitigates relationships. Maybe this is not to be used in the model. It is more generic to use Perdurant causes Perdurant. We may consider that 
	
// collaborative occurrence management versioning. There are two perspectives the perspective of a Service Provider (SP)or the Regulator (R). This is suffiecient for the legislation targeting the communication from SP to R. Additionally the SP and R will need to have also
//	- SafetyIssue extends Event
//	- which are the occurrence reports which belong to this category
	// Version of the documentation of the colaborative management of an Occurrence 
    public static final String InitialReport = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#InitialReport"; // "http://onto.fel.cvut.cz/ontologies/aviation/core#initial-report"
//    public static final String Intruder = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#Intruder";
    public static final String InvestigationReport = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#InvestigationReport"; // "http://onto.fel.cvut.cz/ontologies/aviation/core#investigation-report"
    public static final String PreliminaryReport = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#PreliminaryReport"; // "http://onto.fel.cvut.cz/ontologies/aviation/core#preliminary-report"

	
    public static final String Location = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#Location"; // "http://onto.fel.cvut.cz/ontologies/aviation-safety/Location"
    public static final String Occurrence = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#Occurrence"; // "http://onto.fel.cvut.cz/ontologies/aviation-safety/occurence_report"
    public static final String Organization = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#Organization"; // "http://onto.fel.cvut.cz/ontologies/ufo/Organization"
    public static final String Person = "http://xmlns.com/foaf/0.1/Person";// "http://onto.fel.cvut.cz/ontologies/ufo/Person"
//    public static final String PersonIntruder = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#PersonIntruder";
// Not used, 
    public static final String Resource = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#Resource";// "http://onto.fel.cvut.cz/ontologies/aviation/documentation#Resource"
	
	// This is the object model of the form prototype for the Runway Incursino event. It is used in eventTypeAssesment Objects and should be generalized. 
//    public static final String RunwayIncursion = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#RunwayIncursion";
//    public static final String Vehicle = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#Vehicle";


	public static final String p_hasOccurrence = "hfttp://krizik.felk.cvut.cz/ontologies/inbas-2015#hasOccurrence";// "http://onto.fel.cvut.cz/ontologies/aviation#has-occurrence"
    public static final String p_hasResource = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasResource";// "http://onto.fel.cvut.cz/ontologies/aviation/documentation#has-resource"
    public static final String p_severityLevel = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#severityLevel";// "http://onto.fel.cvut.cz/ontologies/aviation#has-severity"
	
	// user profile onotology - profile is a logical record which documents the participation of an Agent in a relationship such as user of an information system.
	// profile data contains several type of inforamtion. Personal information e.g. name, birth date. Account identitfication, e.g. username and password is a unique identifier accross the IS. Preferences, e.g. prefered language, interests. 
    public static final String p_firstName = "http://xmlns.com/foaf/0.1/firstName";
    public static final String p_lastName = "http://xmlns.com/foaf/0.1/lastName"; 
	// "http://onto.fel.cvut.cz/ontologies/aviation/core#user-profile"
    public static final String p_label = "http://www.w3.org/2000/01/rdf-schema#label"; 
    public static final String p_password = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#password";// "http://onto.fel.cvut.cz/ontologies/aviation/core#has-password"
    public static final String p_username = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#username";// "http://onto.fel.cvut.cz/ontologies/aviation/core#has-username"
    public static final String p_hasEventType = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasEventType";// "rdf:type" 
    public static final String p_startTime = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#occurrenceStartTime";//"http://onto.fel.cvut.cz/ontologies/aviation/core#has-start-time"
    public static final String p_endTime = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#occurrenceEndTime";//"http://onto.fel.cvut.cz/ontologies/aviation/core#has-end-time"
	//Each organization has its own safet occurrence investigation documentation (SOID) lifecycle. The strategy of sharing SOIDs about the same occurrence among numerous organizations is typically based on sharing snapshots of the SOID in specific phases of the investigation lifecycle. For example after observing a SO a SP will decide whether it is a reportable one. If so the SP will continue with collection of basic infromation about the SO. The collection of information might turn into investigation of root caus analysis. The SP shares its SOID with the R in two specific phases. First when collecting initial basic information, e.g. time, location of the occurren, narative description, some categorization. And second when the investigation is finished and root causes are found. 
	// The process of creation and management of SOID within an organization is well established. A GUI of information system tailred for a concrete organization should incorportate this process/lifecycel in order to keep documenting bestpractises.
	// The GUI of IS should also take into account basic abstract SOID concepts inorder to be able to visualize and work with foring SOID snapshots from documentation process from other organizations. 
	// ReportingPhase - a phase from a specific SOID lifecycle. Use uri "http://onto.fel.cvut.cz/ontologies/aviation/core#Reporting-Phase"
	// DocumentVersion - the version of the document
    public static final String p_reportingPhase = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#reportingPhase";// 
    public static final String p_dateCreated = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#dateCreated";//"http://onto.fel.cvut.cz/ontologies/aviation/core#has-createion-time"
	// should we store that information? can we compute it from the history? should we have a question about this information?
    public static final String p_dateLastEdited = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#dateLastEdited"; // "http://onto.fel.cvut.cz/ontologies/aviation/core#last-edit-date"
    public static final String p_description = "http://purl.org/dc/terms/description";// "http://onto.fel.cvut.cz/ontologies/aviation/core#has-description"
    public static final String p_hasAuthor = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#has-author"; // "http://onto.fel.cvut.cz/ontologies/documentation/hasAuthor"
    public static final String p_lastEditedBy = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#lastEditedBy"; // "http://onto.fel.cvut.cz/ontologies/aviation/documentation#has-last-editor"
	
	// this should more generic, there might be changes in the versions based on the organization. For example UCL requested to remove this phase for now.
    public static final String p_hasInitialReport = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasInitialReport"; // "http://onto.fel.cvut.cz/ontologies/aviation/documentation#has-document-snapshots"
    public static final String p_hasCorrectiveMeasure = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasCorrectiveMeasure";// "http://onto.fel.cvut.cz/ontologies/aviation/core#has-corrective-measure"
    public static final String p_hasEventTypeAssessment = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasEventTypeAssessment"; // rdf:type
//    public static final String p_registration = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#registration";
//    public static final String p_stateOfRegistry = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#stateOfRegistry";
//    public static final String p_flightNumber = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#FlightNumber";
//    public static final String p_flightPhase = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#flightPhase";
//    public static final String p_operationType = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#operationType";
//    public static final String p_lastDeparturePoint = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#lastDeparturePoint";
//    public static final String p_plannedDestination = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#plannedDestination";
//    public static final String p_callSign = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#callSign";
//    public static final String p_hasOperator = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasOperator";
//    public static final String p_lowVisibilityProcedure = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#lowVisibilityProcedure";
//    public static final String p_vehicleType = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#vehicleType";
//    public static final String p_controlledByAts = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#isControlledByAts";
//    public static final String p_radio = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasRadio";
//    public static final String p_activityDescription = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#activityDescription";
    public static final String p_memberOf = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#memberOf"; // "http://onto.fel.cvut.cz/ontologies/aviation-safety/is_employee_of"
    public static final String p_personCategory = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#personCategory"; // "rdf:type"
    public static final String p_organizationCode = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#code"; // "http://onto.fel.cvut.cz/ontologies/aviation/core#has-identifier"
    public static final String p_eventType = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#type"; // "rdf:type"
    public static final String p_revision = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#revision"; // "http://onto.fel.cvut.cz/ontologies/aviation/core#has-snapshot-identifier"

//    public static final String p_hasIncursion = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasRunwayIncursion";
//    public static final String p_hasClearedAircraft = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasClearedAircraft";
//    public static final String p_hasIntruder = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasIntruder";
//    public static final String p_hasAircraft = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasAircraft";
//    public static final String p_hasVehicle = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasVehicle";
//    public static final String p_hasPersonIntruder = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasPersonIntruder";
    public static final String p_hasLocation = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasLocation"; // "http://onto.fel.cvut.cz/ontologies/aviation-safety/has_location"

    public static final String p_hasChild = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasChild"; // "http://onto.fel.cvut.cz/ontologies/ufo/has_part"
    public static final String p_hasCause = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasCause"; // "http://onto.fel.cvut.cz/ontologies/aviation-safety/is_caused_by"
    public static final String p_hasMitigation = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasMitigation"; // "http://onto.fel.cvut.cz/ontologies/aviation-safety/is_mitigated_by"
	// This is redundant. Use hasCause.
    public static final String p_hasFactor = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasFactor"; 
    public static final String p_hasContribution = "http://onto.fel.cvut.cz/ontologies/aviation-safety/is_contributed_by";
    public static final String p_hasKey = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#hasKey"; // "http://onto.fel.cvut.cz/ontologies/aviation/core#has-document-identifier"
    public static final String p_fileNumber = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#fileNumber";
	
    public static final String p_dtoClass = "http://krizik.felk.cvut.cz/ontologies/inbas-2015#dtoClass";
}
