PREFIX stamp: <http://onto.fel.cvut.cz/ontologies/stamp/>
PREFIX bizagi: <http://bizagi.com/package/>
PREFIX ufo: <http://onto.fel.cvut.cz/ontologies/ufo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?e stamp:next ?ce.
} WHERE {
  ?f a stamp:next;
    stamp:from-structure-component ?e;
    stamp:to-structure-component ?ce.
  ?e a ufo:event-type.
  ?ce a ufo:event-type.
}