#
# Generic query to get event types
#
BASE <http://onto.fel.cvut.cz/ontologies/aviation-safety/>

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

PREFIX eccairs-model: <http://onto.fel.cvut.cz/ontologies/eccairs/model/>
PREFIX eccairs: <http://onto.fel.cvut.cz/ontologies/eccairs/>
PREFIX eccairs-current: <http://onto.fel.cvut.cz/ontologies/eccairs/aviation-3.4.0.2/>
PREFIX ufo: <http://onto.fel.cvut.cz/ontologies/ufo/>
PREFIX er: <http://dev.inbas.cz/rdf4j-server/repositories/>
PREFIX stamp: <http://onto.fel.cvut.cz/ontologies/stamp/>
PREFIX bpmn: <http://onto.fel.cvut.cz/ontologies/bpmn/>

CONSTRUCT {
  ?term rdfs:label ?label ;
        a ?type ;
        rdfs:comment ?comment ;
} WHERE {
    { # ,eda terms
        ?term a ufo:event-type .
                # add all labels - not everything is returned due to missing labels
                OPTIONAL { ?term rdfs:label ?label.}
                OPTIONAL {?term rdfs:comment ?comment. }
                OPTIONAL {
                    ?term a stamp:unsafe-event.
                    BIND(stamp:unsafe-event as ?unsafe)
                }
                OPTIONAL {
                    ?term a bpmn:flow-control-event-type.
                    BIND(bpmn:flow-control-event-type as ?flowControl)
                }
                OPTIONAL {
                    ?term a bpmn:process-start.
                    BIND(bpmn:process-start as ?flowControl)
                }
                OPTIONAL {
                    ?term a bpmn:intermediate-event.
                    BIND(bpmn:intermediate-event as ?flowControl)
                }
                OPTIONAL {
                    ?term a bpmn:process-end.
                    BIND(bpmn:process-end as ?flowControl)
                }
                BIND( COALESCE(?unsafe, ?flowControl, ufo:event-type) as ?type )
    }
}
