PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

PREFIX ufo: <http://onto.fel.cvut.cz/ontologies/ufo/>
PREFIX doc: <http://onto.fel.cvut.cz/ontologies/documentation/>
PREFIX rt: <http://onto.fel.cvut.cz/ontologies/reporting-tool/>
PREFIX stamp: <http://onto.fel.cvut.cz/ontologies/stamp/>

PREFIX er: <http://dev.inbas.cz/rdf4j-server/repositories/>

SELECT ?event_type ?controlled_process ?controller (COUNT(DISTINCT ?et) AS ?count) WHERE {
  ?report doc:documents ?occurrence .

    FILTER NOT EXISTS {
      ?report <http://onto.fel.cvut.cz/ontologies/reporting-tool/model/has_next_revision> ?y .
    }

  ?occurrence ufo:has_part+ ?et .

  ?et a stamp:unsafe-event ;
    rt:has_event_type ?event_e_t .
  OPTIONAL {
    SERVICE SILENT er:eccairs-aviation-3.4.0.2 {
      ?event_e_t rdfs:label ?event_type.
    }
  }
  OPTIONAL {
    SERVICE SILENT er:eccairs-aviation-1.3.0.8 {
      ?event_e_t rdfs:label ?event_type.
    }
  }
  OPTIONAL {
    SERVICE SILENT er:inbas-model-2016-01-21:22-46-17 {
      ?event_e_t rdfs:label ?event_type.
    }
  }
  OPTIONAL {
      SERVICE SILENT er:stamp {
        ?event_e_t rdfs:label ?event_type.
      }
    }
  OPTIONAL {
    ?et aso:has_factor+ ?cp .
    ?cp a stamp:controlled-process-type .

    OPTIONAL {
      SERVICE SILENT er:stamp {
        ?cp rdfs:label ?controlled_process .
      }
    }

    OPTIONAL {
        ?cp ufo:has_participant ?ctrl .
        ?ctrl a stamp:controller-type .

        OPTIONAL {
          SERVICE SILENT er:stamp {
            ?cp rdfs:label ?controller.
          }
        }
    }
  }
}
GROUP BY ?event_type ?controlled_process ?controller
ORDER BY desc(?count) asc(?event_type)
