PREFIX e-m: <http://onto.fel.cvut.cz/ontologies/eccairs/model/>
PREFIX e-a-3.4.0.2: <http://onto.fel.cvut.cz/ontologies/eccairs/aviation-3.4.0.2/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?series_iri rdfs:label ?aircraft_label .
} WHERE {
 SERVICE <http://dev.inbas.cz/openrdf-sesame/repositories/eccairs-aviation-3.4.0.2> {
    e-a-3.4.0.2:vl-a-21 e-m:has-child ?manufacturer_iri .
      OPTIONAL {
        ?manufacturer_iri e-m:has-child ?model_iri ;
                          e-m:has-description ?manufacturer_label.
        OPTIONAL {
          ?model_iri e-m:has-child ?series_iri ;
                     e-m:has-description ?model_label.
           OPTIONAL {
             ?series_iri e-m:has-description ?series_label.
           }
        }
      }
  }
  BIND (CONCAT(STR(COALESCE(?manufacturer_label, "")), " ", STR(COALESCE(?model_label, "")), " ", STR(COALESCE(?series_label, ""))) as ?aircraft_label)
}
