PREFIX e-m: <http://onto.fel.cvut.cz/ontologies/eccairs/model/>
PREFIX e-a-3.4.0.2: <http://onto.fel.cvut.cz/ontologies/eccairs/aviation-3.4.0.2/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
    ?operator rdfs:label ?label ;
        rdfs:comment ?description .
} WHERE {
    SERVICE <http://dev.inbas.cz/openrdf-sesame/repositories/eccairs-aviation-3.4.0.2> {
     e-a-3.4.0.2:vl-a-215 e-m:has-child ?country .
          OPTIONAL {
                ?country e-m:has-child ?operator ;
                OPTIONAL {
                      ?operator e-m:has-description ?label.
                      ?operator rdfs:label ?description .
                }
          }
  }
} ORDER BY ?operator
