#
# Gets locations for the audit module
#
BASE <http://onto.fel.cvut.cz/ontologies/aviation-safety/>

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

PREFIX eccairs-model: <http://onto.fel.cvut.cz/ontologies/eccairs/model/>
PREFIX eccairs: <http://onto.fel.cvut.cz/ontologies/eccairs/>
PREFIX a-s: <http://onto.fel.cvut.cz/ontologies/aviation-safety/>
PREFIX eccairs-current: <http://onto.fel.cvut.cz/ontologies/eccairs/aviation-3.4.0.2/>

CONSTRUCT {
  ?term rdfs:label ?label ;
    a a-s:Location.
} WHERE {
  SERVICE <http://dev.inbas.cz/openrdf-sesame/repositories/eccairs-aviation-3.4.0.2> {
    SERVICE <http://dev.inbas.cz/openrdf-sesame/repositories/sisel-dev> {
      GRAPH <http://onto.fel.cvut.cz/ontologies/report/ucl/old/options/locations>{
        ?term a a-s:Location.
      }
    }
    ?term rdfs:label ?label.
  }
}