
package cz.cvut.kbss.onto.safety.stamp;



/**
 * This class was generated by OWL2Java 0.13.1
 * 
 */
public class Vocabulary {

    public final static String ONTOLOGY_IRI_ = "http://onto.fel.cvut.cz/ontologies/stamp/";
    public final static String ONTOLOGY_IRI_stamp_risk_hazard_causality = "http://onto.fel.cvut.cz/ontologies/stamp-risk-hazard-causality";
    public final static String ONTOLOGY_IRI_stamp_hazard_profile = "http://onto.fel.cvut.cz/ontologies/stamp-hazard-profile";
    public final static String ONTOLOGY_IRI_stamp_control_loop = "http://onto.fel.cvut.cz/ontologies/stamp-control-loop";
    public final static String ONTOLOGY_IRI_stamp_control_system = "http://onto.fel.cvut.cz/ontologies/stamp-control-system";
    public final static String ONTOLOGY_IRI_stamp_generated = "http://onto.fel.cvut.cz/ontologies/stamp-generated";
    public final static String ONTOLOGY_IRI__A = "http://onto.fel.cvut.cz/ontologies/stamptaxonomy/";
    public final static String ONTOLOGY_IRI__A_A = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/";
    public final static String ONTOLOGY_IRI_stamp_constraints = "http://onto.fel.cvut.cz/ontologies/stamp-constraints";
    public final static String s_c_Thing = "http://www.w3.org/2002/07/owl#Thing";
    public final static String s_c_Actuator_relatd_factors = "http://onto.fel.cvut.cz/ontologies/stamp/Actuator_relatd_factors";
    public final static String s_c_Appropriate_control_actions_were_provided_but_not_followed = "http://onto.fel.cvut.cz/ontologies/stamp/Appropriate_control_actions_were_provided_but_not_followed";
    public final static String s_c_Communication_flaw = "http://onto.fel.cvut.cz/ontologies/stamp/Communication_flaw";
    public final static String s_c_Control_action_provided_at_wrong_time = "http://onto.fel.cvut.cz/ontologies/stamp/Control_action_provided_at_wrong_time";
    public final static String s_c_Control_action_was_not_provided = "http://onto.fel.cvut.cz/ontologies/stamp/Control_action_was_not_provided";
    public final static String s_c_Controller_related_factors = "http://onto.fel.cvut.cz/ontologies/stamp/Controller_related_factors";
    public final static String s_c_Delayed_operations = "http://onto.fel.cvut.cz/ontologies/stamp/Delayed_operations";
    public final static String s_c_Inadequate_actuator_operation = "http://onto.fel.cvut.cz/ontologies/stamp/Inadequate_actuator_operation";
    public final static String s_c_Inadequate_enforcement_of_constraints = "http://onto.fel.cvut.cz/ontologies/stamp/Inadequate_enforcement_of_constraints";
    public final static String s_c_Inadequate_execution_of_control_actions = "http://onto.fel.cvut.cz/ontologies/stamp/Inadequate_execution_of_control_actions";
    public final static String s_c_Process_model__incomplete = "http://onto.fel.cvut.cz/ontologies/stamp/Process_model__incomplete";
    public final static String s_c_Process_model_inconsistent = "http://onto.fel.cvut.cz/ontologies/stamp/Process_model_inconsistent";
    public final static String s_c_Process_model_incorrect = "http://onto.fel.cvut.cz/ontologies/stamp/Process_model_incorrect";
    public final static String s_c_Process_model_related_factors = "http://onto.fel.cvut.cz/ontologies/stamp/Process_model_related_factors";
    public final static String s_c_Quality = "http://onto.fel.cvut.cz/ontologies/stamp/Quality";
    public final static String s_c_Safety_constraint_is_not_enforced_by_the_controller = "http://onto.fel.cvut.cz/ontologies/stamp/Safety_constraint_is_not_enforced_by_the_controller";
    public final static String s_c_Sensor_related_factors = "http://onto.fel.cvut.cz/ontologies/stamp/Sensor_related_factors";
    public final static String s_c_Unsafe_control_action_provided = "http://onto.fel.cvut.cz/ontologies/stamp/Unsafe_control_action_provided";
    public final static String s_c_accident = "http://onto.fel.cvut.cz/ontologies/stamp/accident";
    public final static String s_c_accustic_sensor_type = "http://onto.fel.cvut.cz/ontologies/stamp/accustic-sensor-type";
    public final static String s_c_action_capability = "http://onto.fel.cvut.cz/ontologies/stamp/action-capability";
    public final static String s_c_action_control_connection = "http://onto.fel.cvut.cz/ontologies/stamp/action-control-connection";
    public final static String s_c_active_control = "http://onto.fel.cvut.cz/ontologies/stamp/active-control";
    public final static String s_c_actuating_event = "http://onto.fel.cvut.cz/ontologies/stamp/actuating-event";
    public final static String s_c_actuator = "http://onto.fel.cvut.cz/ontologies/stamp/actuator";
    public final static String s_c_actuator_type = "http://onto.fel.cvut.cz/ontologies/stamp/actuator-type";
    public final static String s_c_algorithm = "http://onto.fel.cvut.cz/ontologies/stamp/algorithm";
    public final static String s_c_applied_too_long = "http://onto.fel.cvut.cz/ontologies/stamp/applied-too-long";
    public final static String s_c_automated_controller = "http://onto.fel.cvut.cz/ontologies/stamp/automated-controller";
    public final static String s_c_automated_controller_type = "http://onto.fel.cvut.cz/ontologies/stamp/automated-controller-type";
    public final static String s_c_behavioral_constraint = "http://onto.fel.cvut.cz/ontologies/stamp/behavioral-constraint";
    public final static String s_c_brain = "http://onto.fel.cvut.cz/ontologies/stamp/brain";
    public final static String s_c_capability = "http://onto.fel.cvut.cz/ontologies/stamp/capability";
    public final static String s_c_causes_connection = "http://onto.fel.cvut.cz/ontologies/stamp/causes-connection";
    public final static String s_c_communication_event = "http://onto.fel.cvut.cz/ontologies/stamp/communication-event";
    public final static String s_c_completeness = "http://onto.fel.cvut.cz/ontologies/stamp/completeness";
    public final static String s_c_condition = "http://onto.fel.cvut.cz/ontologies/stamp/condition";
    public final static String s_c_conditional_next = "http://onto.fel.cvut.cz/ontologies/stamp/conditional-next";
    public final static String s_c_consistency = "http://onto.fel.cvut.cz/ontologies/stamp/consistency";
    public final static String s_c_constraint = "http://onto.fel.cvut.cz/ontologies/stamp/constraint";
    public final static String s_c_control = "http://onto.fel.cvut.cz/ontologies/stamp/control";
    public final static String s_c_control_action = "http://onto.fel.cvut.cz/ontologies/stamp/control-action";
    public final static String s_c_control_capability = "http://onto.fel.cvut.cz/ontologies/stamp/control-capability";
    public final static String s_c_control_event_type = "http://onto.fel.cvut.cz/ontologies/stamp/control-event-type";
    /**
     * This is an abstract class for describing feedback control loops. Control loops descibed on this level of abstraction do not specify how and what is the goal of control.
     * To specify different types of goals subtype this class and add specific descriptions of how describe the goal of the control loop. For example see the safety-control-loop.
     * 
     */
    public final static String s_c_control_loop = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop";
    public final static String s_c_control_loop_type = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-type";
    public final static String s_c_control_responsibility = "http://onto.fel.cvut.cz/ontologies/stamp/control-responsibility";
    public final static String s_c_control_structure = "http://onto.fel.cvut.cz/ontologies/stamp/control-structure";
    public final static String s_c_control_structure_component = "http://onto.fel.cvut.cz/ontologies/stamp/control-structure-component";
    public final static String s_c_control_structure_connection = "http://onto.fel.cvut.cz/ontologies/stamp/control-structure-connection";
    public final static String s_c_control_structure_element = "http://onto.fel.cvut.cz/ontologies/stamp/control-structure-element";
    public final static String s_c_controlled_process = "http://onto.fel.cvut.cz/ontologies/stamp/controlled-process";
    public final static String s_c_controlled_process_type = "http://onto.fel.cvut.cz/ontologies/stamp/controlled-process-type";
    public final static String s_c_controller = "http://onto.fel.cvut.cz/ontologies/stamp/controller";
    public final static String s_c_controller_algorithm = "http://onto.fel.cvut.cz/ontologies/stamp/controller-algorithm";
    public final static String s_c_controller_algorithm_change = "http://onto.fel.cvut.cz/ontologies/stamp/controller-algorithm-change";
    public final static String s_c_controller_algorithm_creation = "http://onto.fel.cvut.cz/ontologies/stamp/controller-algorithm-creation";
    public final static String s_c_controller_command_action = "http://onto.fel.cvut.cz/ontologies/stamp/controller-command-action";
    public final static String s_c_controller_current_process_state = "http://onto.fel.cvut.cz/ontologies/stamp/controller-current-process-state";
    public final static String s_c_controller_current_process_state_perception = "http://onto.fel.cvut.cz/ontologies/stamp/controller-current-process-state-perception";
    public final static String s_c_controller_decision_making = "http://onto.fel.cvut.cz/ontologies/stamp/controller-decision-making";
    public final static String s_c_controller_process_model = "http://onto.fel.cvut.cz/ontologies/stamp/controller-process-model";
    public final static String s_c_controller_process_model_change = "http://onto.fel.cvut.cz/ontologies/stamp/controller-process-model-change";
    public final static String s_c_controller_process_model_creation = "http://onto.fel.cvut.cz/ontologies/stamp/controller-process-model-creation";
    public final static String s_c_controller_type = "http://onto.fel.cvut.cz/ontologies/stamp/controller-type";
    public final static String s_c_controller_brain = "http://onto.fel.cvut.cz/ontologies/stamp/controller_brain";
    public final static String s_c_correctness = "http://onto.fel.cvut.cz/ontologies/stamp/correctness";
    public final static String s_c_factor = "http://onto.fel.cvut.cz/ontologies/stamp/factor";
    public final static String s_c_factor_type = "http://onto.fel.cvut.cz/ontologies/stamp/factor-type";
    public final static String s_c_feedback_capability = "http://onto.fel.cvut.cz/ontologies/stamp/feedback-capability";
    public final static String s_c_feedback_control_connection = "http://onto.fel.cvut.cz/ontologies/stamp/feedback-control-connection";
    public final static String s_c_general_constraint = "http://onto.fel.cvut.cz/ontologies/stamp/general-constraint";
    public final static String s_c_hazard = "http://onto.fel.cvut.cz/ontologies/stamp/hazard";
    public final static String s_c_hazard_state = "http://onto.fel.cvut.cz/ontologies/stamp/hazard-state";
    public final static String s_c_hazard_state_type = "http://onto.fel.cvut.cz/ontologies/stamp/hazard-state-type";
    public final static String s_c_hazardous_disposition = "http://onto.fel.cvut.cz/ontologies/stamp/hazardous-disposition";
    public final static String s_c_inadequate_feedback = "http://onto.fel.cvut.cz/ontologies/stamp/inadequate-feedback";
    public final static String s_c_information_capability = "http://onto.fel.cvut.cz/ontologies/stamp/information-capability";
    public final static String s_c_information_control_connection = "http://onto.fel.cvut.cz/ontologies/stamp/information-control-connection";
    public final static String s_c_loss_event = "http://onto.fel.cvut.cz/ontologies/stamp/loss-event";
    public final static String s_c_loss_event_type = "http://onto.fel.cvut.cz/ontologies/stamp/loss-event-type";
    public final static String s_c_measurement = "http://onto.fel.cvut.cz/ontologies/stamp/measurement";
    public final static String s_c_mental = "http://onto.fel.cvut.cz/ontologies/stamp/mental";
    public final static String s_c_must_not_occur_after = "http://onto.fel.cvut.cz/ontologies/stamp/must-not-occur-after";
    public final static String s_c_must_not_occur_before = "http://onto.fel.cvut.cz/ontologies/stamp/must-not-occur-before";
    public final static String s_c_must_occur_after = "http://onto.fel.cvut.cz/ontologies/stamp/must-occur-after";
    public final static String s_c_must_occur_before = "http://onto.fel.cvut.cz/ontologies/stamp/must-occur-before";
    public final static String s_c_nary_structure_connection = "http://onto.fel.cvut.cz/ontologies/stamp/nary-structure-connection";
    public final static String s_c_next = "http://onto.fel.cvut.cz/ontologies/stamp/next";
    public final static String s_c_not_providing = "http://onto.fel.cvut.cz/ontologies/stamp/not-providing";
    public final static String s_c_object_at_risk = "http://onto.fel.cvut.cz/ontologies/stamp/object_at_risk";
    public final static String s_c_occurrence = "http://onto.fel.cvut.cz/ontologies/stamp/occurrence";
    public final static String s_c_out_of_order = "http://onto.fel.cvut.cz/ontologies/stamp/out-of-order";
    public final static String s_c_passive_control = "http://onto.fel.cvut.cz/ontologies/stamp/passive-control";
    public final static String s_c_people_group = "http://onto.fel.cvut.cz/ontologies/stamp/people-group";
    public final static String s_c_person = "http://onto.fel.cvut.cz/ontologies/stamp/person";
    public final static String s_c_person_controller = "http://onto.fel.cvut.cz/ontologies/stamp/person-controller";
    public final static String s_c_person_controller_type = "http://onto.fel.cvut.cz/ontologies/stamp/person-controller-type";
    public final static String s_c_process = "http://onto.fel.cvut.cz/ontologies/stamp/process";
    public final static String s_c_process_changes = "http://onto.fel.cvut.cz/ontologies/stamp/process-changes";
    public final static String s_c_process_components = "http://onto.fel.cvut.cz/ontologies/stamp/process-components";
    public final static String s_c_process_connection = "http://onto.fel.cvut.cz/ontologies/stamp/process-connection";
    public final static String s_c_process_control_connection = "http://onto.fel.cvut.cz/ontologies/stamp/process-control-connection";
    public final static String s_c_process_disturbance = "http://onto.fel.cvut.cz/ontologies/stamp/process-disturbance";
    public final static String s_c_process_disturbances = "http://onto.fel.cvut.cz/ontologies/stamp/process-disturbances";
    public final static String s_c_process_input = "http://onto.fel.cvut.cz/ontologies/stamp/process-input";
    public final static String s_c_process_instance = "http://onto.fel.cvut.cz/ontologies/stamp/process-instance";
    /**
     * This is a general process-model not the process model of the controller. The term for the process model is 'stamp:controller-process-model'.
     * 
     */
    public final static String s_c_process_model = "http://onto.fel.cvut.cz/ontologies/stamp/process-model";
    public final static String s_c_process_output = "http://onto.fel.cvut.cz/ontologies/stamp/process-output";
    public final static String s_c_process_structure = "http://onto.fel.cvut.cz/ontologies/stamp/process-structure";
    public final static String s_c_process_structure_component = "http://onto.fel.cvut.cz/ontologies/stamp/process-structure-component";
    public final static String s_c_process_model_A = "http://onto.fel.cvut.cz/ontologies/stamp/process_model";
    public final static String s_c_processing_of_feedback = "http://onto.fel.cvut.cz/ontologies/stamp/processing-of-feedback";
    public final static String s_c_providing = "http://onto.fel.cvut.cz/ontologies/stamp/providing";
    public final static String s_c_rational_object = "http://onto.fel.cvut.cz/ontologies/stamp/rational_object";
    public final static String s_c_resulting_situation = "http://onto.fel.cvut.cz/ontologies/stamp/resulting_situation";
    public final static String s_c_risk_enabler = "http://onto.fel.cvut.cz/ontologies/stamp/risk_enabler";
    public final static String s_c_risk_event = "http://onto.fel.cvut.cz/ontologies/stamp/risk_event";
    public final static String s_c_safety_control = "http://onto.fel.cvut.cz/ontologies/stamp/safety-control";
    public final static String s_c_safety_control_loop_type = "http://onto.fel.cvut.cz/ontologies/stamp/safety-control-loop-type";
    /**
     * safety control loop. extends the super class control-loop by adding a goal, i.e. control for unwanted event
     * 
     */
    public final static String s_c_safty_control_loop = "http://onto.fel.cvut.cz/ontologies/stamp/safty-control-loop";
    public final static String s_c_sensing_event = "http://onto.fel.cvut.cz/ontologies/stamp/sensing-event";
    public final static String s_c_sensor = "http://onto.fel.cvut.cz/ontologies/stamp/sensor";
    public final static String s_c_sensor_type = "http://onto.fel.cvut.cz/ontologies/stamp/sensor-type";
    /**
     * severity
     * 
     */
    public final static String s_c_severity = "http://onto.fel.cvut.cz/ontologies/stamp/severity";
    public final static String s_c_stamp_event = "http://onto.fel.cvut.cz/ontologies/stamp/stamp-event";
    public final static String s_c_stamp_event_type = "http://onto.fel.cvut.cz/ontologies/stamp/stamp-event-type";
    public final static String s_c_stamp_object = "http://onto.fel.cvut.cz/ontologies/stamp/stamp-object";
    public final static String s_c_state_constraint = "http://onto.fel.cvut.cz/ontologies/stamp/state-constraint";
    public final static String s_c_stopped_too_soon = "http://onto.fel.cvut.cz/ontologies/stamp/stopped-too-soon";
    public final static String s_c_structure = "http://onto.fel.cvut.cz/ontologies/stamp/structure";
    public final static String s_c_structure_component = "http://onto.fel.cvut.cz/ontologies/stamp/structure-component";
    public final static String s_c_structure_connection = "http://onto.fel.cvut.cz/ontologies/stamp/structure-connection";
    public final static String s_c_structure_element = "http://onto.fel.cvut.cz/ontologies/stamp/structure-element";
    public final static String s_c_structured_control = "http://onto.fel.cvut.cz/ontologies/stamp/structured-control";
    public final static String s_c_structured_structure_element = "http://onto.fel.cvut.cz/ontologies/stamp/structured-structure-element";
    public final static String s_c_too_early = "http://onto.fel.cvut.cz/ontologies/stamp/too-early";
    public final static String s_c_too_late = "http://onto.fel.cvut.cz/ontologies/stamp/too-late";
    public final static String s_c_type = "http://onto.fel.cvut.cz/ontologies/stamp/type";
    public final static String s_c_unsafe_action_capability = "http://onto.fel.cvut.cz/ontologies/stamp/unsafe-action-capability";
    public final static String s_c_unsafe_control_capability = "http://onto.fel.cvut.cz/ontologies/stamp/unsafe-control-capability";
    public final static String s_c_unsafe_event = "http://onto.fel.cvut.cz/ontologies/stamp/unsafe-event";
    public final static String s_c_unsafe_feedback_capability = "http://onto.fel.cvut.cz/ontologies/stamp/unsafe-feedback-capability";
    public final static String s_c_unwanted_event = "http://onto.fel.cvut.cz/ontologies/stamp/unwanted-event";
    public final static String s_c_variable = "http://onto.fel.cvut.cz/ontologies/stamp/variable";
    public final static String s_c_visual_sensor_type = "http://onto.fel.cvut.cz/ontologies/stamp/visual-sensor-type";
    public final static String s_c__unsafe_colaboration = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/_unsafe-colaboration";
    public final static String s_c__unsafe_communication = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/_unsafe-communication";
    public final static String s_c__unsafe_cooperation = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/_unsafe-cooperation";
    public final static String s_c__unsage_coordination = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/_unsage-coordination";
    public final static String s_c_accident_A = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/accident";
    public final static String s_c_appropriate_control_actions_were_provided_but_not_followed = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/appropriate-control-actions-were-provided-but-not-followed";
    public final static String s_c_changes_over_time = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/changes-over-time";
    public final static String s_c_communication_flaw___feedback_communication_channel = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/communication-flaw---feedback-communication-channel";
    public final static String s_c_communication_flaw__control_communication_channel = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/communication-flaw--control-communication-channel";
    public final static String s_c_component_failure = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/component-failure";
    public final static String s_c_conflicting_control_actions = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/conflicting-control-actions";
    public final static String s_c_control_action_provided_at_wrong_time = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/control-action-provided-at-wrong-time";
    public final static String s_c_control_action_was_not_provided = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/control-action-was-not-provided";
    public final static String s_c_control_input_or_external_information_wrong_or_missing = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/control-input-or-external-information-wrong-or-missing";
    public final static String s_c_controlled_process_issues = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/controlled-process-issues";
    public final static String s_c_delayed_operations = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/delayed-operations";
    public final static String s_c_design_of_control_algorithm_does_not_enforce_constraint = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/design-of-control-algorithm-does-not-enforce-constraint";
    public final static String s_c_feedback_delays = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/feedback-delays";
    public final static String s_c_feedback_not_provided_in_system_design = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/feedback-not-provided-in-system-design";
    public final static String s_c_flaws_in_creation_process = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/flaws-in-creation-process";
    public final static String s_c_flaws_in_updating_process__asynchronous_evolution = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/flaws-in-updating-process--asynchronous-evolution";
    public final static String s_c_inadequate_actuator_operation = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/inadequate-actuator-operation";
    public final static String s_c_inadequate_coordination_among_controllers__boundary_and_overlap_areas = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/inadequate-coordination-among-controllers--boundary-and-overlap-areas";
    public final static String s_c_inadequate_enforcement_of_constraints = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/inadequate-enforcement-of-constraints";
    public final static String s_c_inadequate_execution_of_control_actions = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/inadequate-execution-of-control-actions";
    public final static String s_c_inadequate_or_missing_feedback = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/inadequate-or-missing-feedback";
    public final static String s_c_inadequate_sensor_operation__incorrect_or_no_information_provided = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/inadequate-sensor-operation--incorrect-or-no-information-provided";
    public final static String s_c_inappropriate_control_action = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/inappropriate-control-action";
    public final static String s_c_incomplete_or_incorrect = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/incomplete-or-incorrect";
    public final static String s_c_incorrect_modification_of_adaptation = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/incorrect-modification-of-adaptation";
    public final static String s_c_ineffective_control_action = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/ineffective-control-action";
    public final static String s_c_measurement_inaccuracies = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/measurement-inaccuracies";
    public final static String s_c_missing_control_action = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/missing-control-action";
    public final static String s_c_misssing_input = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/misssing-input";
    public final static String s_c_process_changes_without_appropriate_change_in_control_algorithm___asynchronous_evolution = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/process-changes-without-appropriate-change-in-control-algorithm---asynchronous-evolution";
    public final static String s_c_process_input_missing_or_wrong = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/process-input-missing-or-wrong";
    public final static String s_c_process_output_contributes__to_system_hazard = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/process-output-contributes--to-system-hazard";
    public final static String s_c_safety_constraint_is_not_enforced_by_the_controller = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/safety-constraint-is-not-enforced-by-the-controller";
    public final static String s_c_stamp_based = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/stamp-based";
    public final static String s_c_time_lag_feedback = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/time-lag-feedback";
    public final static String s_c_time_lags = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/time-lags";
    public final static String s_c_unidentified_hazard = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/unidentified-hazard";
    public final static String s_c_unidentified_or_out_of_range__disturbance = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/unidentified-or-out-of-range--disturbance";
    public final static String s_c_unsafe_actuators = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/unsafe-actuators";
    public final static String s_c_unsafe_button = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/unsafe-button";
    public final static String s_c_unsafe_control_action_provided = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/unsafe-control-action-provided";
    /**
     * Notes:
     * There are different event chains which lead to a unsafe control algorithm.
     * 
     */
    public final static String s_c_unsafe_control_algorithm = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/unsafe-control-algorithm";
    public final static String s_c_unsafe_controlled_processes = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/unsafe-controlled-processes";
    public final static String s_c_unsafe_human_control_algorithm = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/unsafe-human-control-algorithm";
    /**
     * example:
     * Using the Black Hawk friendly fire example again, the F-15 pilots patrolling the no-fly zone were given instructions to switch to a non-jammed radio mode for a list of aircraft types that did not have the ability to interpret jammed broadcasts. Black Hawk helicopters had not been upgraded with new anti-jamming technology but were omitted from the list and so could not hear the F-15 radio broadcasts. Other types of missing or wrong noncontrol inputs may also affect the operation of the controller.
     * 
     */
    public final static String s_c_unsafe_input = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/unsafe-input";
    public final static String s_c_unsafe_machine_control_algorithm = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/unsafe-machine-control-algorithm";
    /**
     * Inconsistent, Incomplete, or Incorrect Process Models
     * 
     */
    public final static String s_c_unsafe_process_model = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/unsafe-process-model";
    public final static String s_c_wrong_input = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop-failure-taxonomy/wrong-input";
    public final static String s_c_perdurant_type = "http://onto.fel.cvut.cz/ontologies/ufo-b-temporal/perdurant-type";
    public final static String s_c_action = "http://onto.fel.cvut.cz/ontologies/ufo/action";
    public final static String s_c_collective = "http://onto.fel.cvut.cz/ontologies/ufo/collective";
    public final static String s_c_endurant = "http://onto.fel.cvut.cz/ontologies/ufo/endurant";
    public final static String s_c_event = "http://onto.fel.cvut.cz/ontologies/ufo/event";
    public final static String s_c_event_type = "http://onto.fel.cvut.cz/ontologies/ufo/event-type";
    public final static String s_c_individual = "http://onto.fel.cvut.cz/ontologies/ufo/individual";
    public final static String s_c_object = "http://onto.fel.cvut.cz/ontologies/ufo/object";
    public final static String s_c_perdurant = "http://onto.fel.cvut.cz/ontologies/ufo/perdurant";
    public final static String s_c_person_A = "http://onto.fel.cvut.cz/ontologies/ufo/person";
    public final static String s_c_physical_object = "http://onto.fel.cvut.cz/ontologies/ufo/physical-object";
    public final static String s_c_quality_universal = "http://onto.fel.cvut.cz/ontologies/ufo/quality-universal";
    public final static String s_c_situation = "http://onto.fel.cvut.cz/ontologies/ufo/situation";
    public final static String s_c_trope = "http://onto.fel.cvut.cz/ontologies/ufo/trope";
    public final static String s_c_universal = "http://onto.fel.cvut.cz/ontologies/ufo/universal";
    public final static String s_p_causes = "http://onto.fel.cvut.cz/ontologies/aviation-safety/causes";
    public final static String s_p_contributes_to = "http://onto.fel.cvut.cz/ontologies/aviation-safety/contributes_to";
    public final static String s_p_is_factor_of = "http://onto.fel.cvut.cz/ontologies/aviation-safety/is_factor_of";
    public final static String s_p_may_be_factor_of = "http://onto.fel.cvut.cz/ontologies/aviation-safety/may_be_factor_of";
    public final static String s_p_may_cause = "http://onto.fel.cvut.cz/ontologies/aviation-safety/may_cause";
    public final static String s_p_may_contributes_to = "http://onto.fel.cvut.cz/ontologies/aviation-safety/may_contributes_to";
    public final static String s_p_may_mitigate = "http://onto.fel.cvut.cz/ontologies/aviation-safety/may_mitigate";
    public final static String s_p_may_prevent = "http://onto.fel.cvut.cz/ontologies/aviation-safety/may_prevent";
    public final static String s_p_mitigates = "http://onto.fel.cvut.cz/ontologies/aviation-safety/mitigates";
    public final static String s_p_prevents = "http://onto.fel.cvut.cz/ontologies/aviation-safety/prevents";
    public final static String s_p_caused = "http://onto.fel.cvut.cz/ontologies/stamp/caused";
    public final static String s_p_constrains = "http://onto.fel.cvut.cz/ontologies/stamp/constrains";
    /**
     * contributes
     * 
     */
    public final static String s_p_contributes_to_A = "http://onto.fel.cvut.cz/ontologies/stamp/contributes_to";
    public final static String s_p_controls = "http://onto.fel.cvut.cz/ontologies/stamp/controls";
    public final static String s_p_controls_for = "http://onto.fel.cvut.cz/ontologies/stamp/controls-for";
    public final static String s_p_derived_from = "http://onto.fel.cvut.cz/ontologies/stamp/derived-from";
    public final static String s_p_designed_to_enforce = "http://onto.fel.cvut.cz/ontologies/stamp/designed-to-enforce";
    public final static String s_p_designed_to_prevent = "http://onto.fel.cvut.cz/ontologies/stamp/designed-to-prevent";
    public final static String s_p_enforces = "http://onto.fel.cvut.cz/ontologies/stamp/enforces";
    public final static String s_p_first_event = "http://onto.fel.cvut.cz/ontologies/stamp/first-event";
    public final static String s_p_from_structure_component = "http://onto.fel.cvut.cz/ontologies/stamp/from-structure-component";
    public final static String s_p_has_actuator = "http://onto.fel.cvut.cz/ontologies/stamp/has-actuator";
    public final static String s_p_has_capability = "http://onto.fel.cvut.cz/ontologies/stamp/has-capability";
    public final static String s_p_has_condition = "http://onto.fel.cvut.cz/ontologies/stamp/has-condition";
    public final static String s_p_has_control_algorithm = "http://onto.fel.cvut.cz/ontologies/stamp/has-control-algorithm";
    public final static String s_p_has_control_loop = "http://onto.fel.cvut.cz/ontologies/stamp/has-control-loop";
    public final static String s_p_has_control_structure = "http://onto.fel.cvut.cz/ontologies/stamp/has-control-structure";
    public final static String s_p_has_control_structure_element_part = "http://onto.fel.cvut.cz/ontologies/stamp/has-control-structure-element-part";
    public final static String s_p_has_controller = "http://onto.fel.cvut.cz/ontologies/stamp/has-controller";
    public final static String s_p_has_enforcement_plan = "http://onto.fel.cvut.cz/ontologies/stamp/has-enforcement-plan";
    public final static String s_p_has_goal = "http://onto.fel.cvut.cz/ontologies/stamp/has-goal";
    public final static String s_p_has_group_member = "http://onto.fel.cvut.cz/ontologies/stamp/has-group-member";
    public final static String s_p_has_manifested_state = "http://onto.fel.cvut.cz/ontologies/stamp/has-manifested-state";
    public final static String s_p_has_person_member = "http://onto.fel.cvut.cz/ontologies/stamp/has-person-member";
    public final static String s_p_has_plan = "http://onto.fel.cvut.cz/ontologies/stamp/has-plan";
    public final static String s_p_has_possible_interaction = "http://onto.fel.cvut.cz/ontologies/stamp/has-possible-interaction";
    public final static String s_p_has_process_model = "http://onto.fel.cvut.cz/ontologies/stamp/has-process-model";
    public final static String s_p_has_process_state = "http://onto.fel.cvut.cz/ontologies/stamp/has-process-state";
    public final static String s_p_has_responsibility = "http://onto.fel.cvut.cz/ontologies/stamp/has-responsibility";
    /**
     * the assertion A has-same-structure-as B, than A has the same structural components as B.
     * 
     */
    public final static String s_p_has_same_structure_as = "http://onto.fel.cvut.cz/ontologies/stamp/has-same-structure-as";
    public final static String s_p_has_sensor = "http://onto.fel.cvut.cz/ontologies/stamp/has-sensor";
    /**
     * This is an event which is unsafe.
     * 
     */
    public final static String s_p_has_unwanted_event = "http://onto.fel.cvut.cz/ontologies/stamp/has-unwanted-event";
    public final static String s_p_in_context = "http://onto.fel.cvut.cz/ontologies/stamp/in-context";
    public final static String s_p_interaction_after = "http://onto.fel.cvut.cz/ontologies/stamp/interaction-after";
    public final static String s_p_interaction_before = "http://onto.fel.cvut.cz/ontologies/stamp/interaction-before";
    public final static String s_p_is_group_member_of = "http://onto.fel.cvut.cz/ontologies/stamp/is-group-member-of";
    public final static String s_p_is_part_of_control_structure = "http://onto.fel.cvut.cz/ontologies/stamp/is-part-of-control-structure";
    public final static String s_p_is_person_member_of = "http://onto.fel.cvut.cz/ontologies/stamp/is-person-member-of";
    public final static String s_p_mitigates_A = "http://onto.fel.cvut.cz/ontologies/stamp/mitigates";
    public final static String s_p_next = "http://onto.fel.cvut.cz/ontologies/stamp/next";
    public final static String s_p_participates_in = "http://onto.fel.cvut.cz/ontologies/stamp/participates_in";
    public final static String s_p_process_connection_from = "http://onto.fel.cvut.cz/ontologies/stamp/process-connection-from";
    public final static String s_p_process_connection_to = "http://onto.fel.cvut.cz/ontologies/stamp/process-connection-to";
    public final static String s_p_process_has_part = "http://onto.fel.cvut.cz/ontologies/stamp/process-has-part";
    public final static String s_p_provides_feedback = "http://onto.fel.cvut.cz/ontologies/stamp/provides-feedback";
    public final static String s_p_second_event = "http://onto.fel.cvut.cz/ontologies/stamp/second-event";
    public final static String s_p_senses = "http://onto.fel.cvut.cz/ontologies/stamp/senses";
    public final static String s_p_source = "http://onto.fel.cvut.cz/ontologies/stamp/source";
    public final static String s_p_to_structure_component = "http://onto.fel.cvut.cz/ontologies/stamp/to-structure-component";
    public final static String s_p_violates = "http://onto.fel.cvut.cz/ontologies/stamp/violates";
    /**
     * categorize
     * 
     */
    public final static String s_p_categorize = "http://onto.fel.cvut.cz/ontologies/stamptaxonomy/categorize";
    public final static String s_p_characterization_of = "http://onto.fel.cvut.cz/ontologies/stamptaxonomy/characterization_of";
    public final static String s_p_contributes_to_A_A = "http://onto.fel.cvut.cz/ontologies/stamptaxonomy/contributes_to";
    /**
     * instance of
     * 
     */
    public final static String s_p_instance_of = "http://onto.fel.cvut.cz/ontologies/stamptaxonomy/instance_of";
    public final static String s_p_causes_A = "http://onto.fel.cvut.cz/ontologies/ufo/causes";
    public final static String s_p_equals = "http://onto.fel.cvut.cz/ontologies/ufo/equals";
    public final static String s_p_has_inherent_moment = "http://onto.fel.cvut.cz/ontologies/ufo/has-inherent-moment";
    public final static String s_p_has_object_part = "http://onto.fel.cvut.cz/ontologies/ufo/has-object-part";
    public final static String s_p_has_participant = "http://onto.fel.cvut.cz/ontologies/ufo/has-participant";
    public final static String s_p_inheres_in = "http://onto.fel.cvut.cz/ontologies/ufo/inheres-in";
    public final static String s_p_is_classified_by = "http://onto.fel.cvut.cz/ontologies/ufo/is-classified-by";
    public final static String s_p_is_manifested_by = "http://onto.fel.cvut.cz/ontologies/ufo/is-manifested-by";
    public final static String s_p_is_object_part_of = "http://onto.fel.cvut.cz/ontologies/ufo/is-object-part-of";
    public final static String s_p_is_part_of = "http://onto.fel.cvut.cz/ontologies/ufo/is-part-of";
    public final static String s_p_is_participant_of = "http://onto.fel.cvut.cz/ontologies/ufo/is-participant-of";
    public final static String s_p_topObjectProperty = "http://www.w3.org/2002/07/owl#topObjectProperty";
    public final static String s_p_description = "http://purl.org/dc/terms/description";
    public final static String s_p_comment = "http://www.w3.org/2000/01/rdf-schema#comment";
    public final static String s_p_label = "http://www.w3.org/2000/01/rdf-schema#label";
    /**
     * This visual sensor is a direct observation of the operational process
     * 
     */
    public final static String s_i_direct_operation_observation = "http://onto.fel.cvut.cz/ontologies/stamp/direct-operation-observation";
    /**
     * this is strictly visual information such as signs and gestures performed by other personel or other people.
     * 
     */
    public final static String s_i_signals_from_other_people = "http://onto.fel.cvut.cz/ontologies/stamp/signals-from-other-people";

}
